/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_DIGITALASSET_CANTON_VERSION_V1_COM_DIGITALASSET_CANTON_VERSION_V1_UNTYPED_VERSIONED_MESSAGE_PB_H_INCLUDED
#define PB_COM_DIGITALASSET_CANTON_VERSION_V1_COM_DIGITALASSET_CANTON_VERSION_V1_UNTYPED_VERSIONED_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* [start UntypedVersionedMessage] */
typedef struct _com_digitalasset_canton_version_v1_UntypedVersionedMessage {
    pb_size_t which_wrapper;
    union {
        pb_bytes_array_t *data;
    };
    int32_t version;
} com_digitalasset_canton_version_v1_UntypedVersionedMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define com_digitalasset_canton_version_v1_UntypedVersionedMessage_init_default {0, {NULL}, 0}
#define com_digitalasset_canton_version_v1_UntypedVersionedMessage_init_zero {0, {NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define com_digitalasset_canton_version_v1_UntypedVersionedMessage_data_tag 1
#define com_digitalasset_canton_version_v1_UntypedVersionedMessage_version_tag 2

/* Struct field encoding specification for nanopb */
#define com_digitalasset_canton_version_v1_UntypedVersionedMessage_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    BYTES,    (wrapper,data,data),   1) \
X(a, STATIC,   SINGULAR, INT32,    version,           2)
#define com_digitalasset_canton_version_v1_UntypedVersionedMessage_CALLBACK NULL
#define com_digitalasset_canton_version_v1_UntypedVersionedMessage_DEFAULT NULL

extern const pb_msgdesc_t com_digitalasset_canton_version_v1_UntypedVersionedMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_digitalasset_canton_version_v1_UntypedVersionedMessage_fields &com_digitalasset_canton_version_v1_UntypedVersionedMessage_msg

/* Maximum encoded size of messages (where known) */
/* com_digitalasset_canton_version_v1_UntypedVersionedMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
