/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GOOGLE_RPC_GOOGLE_RPC_ERROR_DETAILS_PB_H_INCLUDED
#define PB_GOOGLE_RPC_GOOGLE_RPC_ERROR_DETAILS_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/duration.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Describes the cause of the error with structured details.

 Example of an error when contacting the "pubsub.googleapis.com" API when it
 is not enabled:

     { "reason": "API_DISABLED"
       "domain": "googleapis.com"
       "metadata": {
         "resource": "projects/123",
         "service": "pubsub.googleapis.com"
       }
     }

 This response indicates that the pubsub.googleapis.com API is not enabled.

 Example of an error that is returned when attempting to create a Spanner
 instance in a region that is out of stock:

     { "reason": "STOCKOUT"
       "domain": "spanner.googleapis.com",
       "metadata": {
         "availableRegions": "us-central1,us-east2"
       }
     } */
typedef struct _google_rpc_ErrorInfo {
    /* The reason of the error. This is a constant value that identifies the
 proximate cause of the error. Error reasons are unique within a particular
 domain of errors. This should be at most 63 characters and match a
 regular expression of `[A-Z][A-Z0-9_]+[A-Z0-9]`, which represents
 UPPER_SNAKE_CASE. */
    char reason[1024];
    /* The logical grouping to which the "reason" belongs. The error domain
 is typically the registered service name of the tool or product that
 generates the error. Example: "pubsub.googleapis.com". If the error is
 generated by some common infrastructure, the error domain must be a
 globally unique value that identifies the infrastructure. For Google API
 infrastructure, the error domain is "googleapis.com". */
    char domain[1024];
    /* Additional structured details about this error.

 Keys must match a regular expression of `[a-z][a-zA-Z0-9-_]+` but should
 ideally be lowerCamelCase. Also, they must be limited to 64 characters in
 length. When identifying the current value of an exceeded limit, the units
 should be contained in the key, not the value.  For example, rather than
 `{"instanceLimit": "100/request"}`, should be returned as,
 `{"instanceLimitPerRequest": "100"}`, if the client exceeds the number of
 instances that can be created in a single (batch) request. */
    pb_callback_t metadata;
} google_rpc_ErrorInfo;

typedef struct _google_rpc_ErrorInfo_MetadataEntry {
    char key[1024];
    char value[1024];
} google_rpc_ErrorInfo_MetadataEntry;

/* Describes when the clients can retry a failed request. Clients could ignore
 the recommendation here or retry when this information is missing from error
 responses.

 It's always recommended that clients should use exponential backoff when
 retrying.

 Clients should wait until `retry_delay` amount of time has passed since
 receiving the error response before retrying.  If retrying requests also
 fail, clients should use an exponential backoff scheme to gradually increase
 the delay between retries based on `retry_delay`, until either a maximum
 number of retries have been reached or a maximum retry delay cap has been
 reached. */
typedef struct _google_rpc_RetryInfo {
    /* Clients should wait at least this long between retrying the same request. */
    bool has_retry_delay;
    google_protobuf_Duration retry_delay;
} google_rpc_RetryInfo;

/* Describes additional debugging info. */
typedef struct _google_rpc_DebugInfo {
    /* The stack trace entries indicating where the error occurred. */
    pb_callback_t stack_entries;
    /* Additional debugging information provided by the server. */
    char detail[1024];
} google_rpc_DebugInfo;

/* Describes how a quota check failed.

 For example if a daily limit was exceeded for the calling project,
 a service could respond with a QuotaFailure detail containing the project
 id and the description of the quota limit that was exceeded.  If the
 calling project hasn't enabled the service in the developer console, then
 a service could respond with the project id and set `service_disabled`
 to true.

 Also see RetryInfo and Help types for other details about handling a
 quota failure. */
typedef struct _google_rpc_QuotaFailure {
    /* Describes all quota violations. */
    pb_callback_t violations;
} google_rpc_QuotaFailure;

/* A message type used to describe a single quota violation.  For example, a
 daily quota or a custom quota that was exceeded. */
typedef struct _google_rpc_QuotaFailure_Violation {
    /* The subject on which the quota check failed.
 For example, "clientip:<ip address of client>" or "project:<Google
 developer project id>". */
    char subject[1024];
    /* A description of how the quota check failed. Clients can use this
 description to find more about the quota configuration in the service's
 public documentation, or find the relevant quota limit to adjust through
 developer console.

 For example: "Service disabled" or "Daily Limit for read operations
 exceeded". */
    char description[1024];
} google_rpc_QuotaFailure_Violation;

/* Describes what preconditions have failed.

 For example, if an RPC failed because it required the Terms of Service to be
 acknowledged, it could list the terms of service violation in the
 PreconditionFailure message. */
typedef struct _google_rpc_PreconditionFailure {
    /* Describes all precondition violations. */
    pb_callback_t violations;
} google_rpc_PreconditionFailure;

/* A message type used to describe a single precondition failure. */
typedef struct _google_rpc_PreconditionFailure_Violation {
    /* The type of PreconditionFailure. We recommend using a service-specific
 enum type to define the supported precondition violation subjects. For
 example, "TOS" for "Terms of Service violation". */
    char type[1024];
    /* The subject, relative to the type, that failed.
 For example, "google.com/cloud" relative to the "TOS" type would indicate
 which terms of service is being referenced. */
    char subject[1024];
    /* A description of how the precondition failed. Developers can use this
 description to understand how to fix the failure.

 For example: "Terms of service not accepted". */
    char description[1024];
} google_rpc_PreconditionFailure_Violation;

/* Describes violations in a client request. This error type focuses on the
 syntactic aspects of the request. */
typedef struct _google_rpc_BadRequest {
    /* Describes all violations in a client request. */
    pb_callback_t field_violations;
} google_rpc_BadRequest;

/* Contains metadata about the request that clients can attach when filing a bug
 or providing other forms of feedback. */
typedef struct _google_rpc_RequestInfo {
    /* An opaque string that should only be interpreted by the service generating
 it. For example, it can be used to identify requests in the service's logs. */
    char request_id[1024];
    /* Any data that was used to serve this request. For example, an encrypted
 stack trace that can be sent back to the service provider for debugging. */
    char serving_data[1024];
} google_rpc_RequestInfo;

/* Describes the resource that is being accessed. */
typedef struct _google_rpc_ResourceInfo {
    /* A name for the type of resource being accessed, e.g. "sql table",
 "cloud storage bucket", "file", "Google calendar"; or the type URL
 of the resource: e.g. "type.googleapis.com/google.pubsub.v1.Topic". */
    char resource_type[1024];
    /* The name of the resource being accessed.  For example, a shared calendar
 name: "example.com_4fghdhgsrgh@group.calendar.google.com", if the current
 error is
 [google.rpc.Code.PERMISSION_DENIED][google.rpc.Code.PERMISSION_DENIED]. */
    char resource_name[1024];
    /* The owner of the resource (optional).
 For example, "user:<owner email>" or "project:<Google developer project
 id>". */
    char owner[1024];
    /* Describes what error is encountered when accessing this resource.
 For example, updating a cloud project may require the `writer` permission
 on the developer console project. */
    char description[1024];
} google_rpc_ResourceInfo;

/* Provides links to documentation or for performing an out of band action.

 For example, if a quota check failed with an error indicating the calling
 project hasn't enabled the accessed service, this can contain a URL pointing
 directly to the right place in the developer console to flip the bit. */
typedef struct _google_rpc_Help {
    /* URL(s) pointing to additional information on handling the current error. */
    pb_callback_t links;
} google_rpc_Help;

/* Describes a URL link. */
typedef struct _google_rpc_Help_Link {
    /* Describes what the link offers. */
    char description[1024];
    /* The URL of the link. */
    char url[1024];
} google_rpc_Help_Link;

/* Provides a localized error message that is safe to return to the user
 which can be attached to an RPC error. */
typedef struct _google_rpc_LocalizedMessage {
    /* The locale used following the specification defined at
 https://www.rfc-editor.org/rfc/bcp/bcp47.txt.
 Examples are: "en-US", "fr-CH", "es-MX" */
    char locale[1024];
    /* The localized error message in the above locale. */
    char message[1024];
} google_rpc_LocalizedMessage;

/* A message type used to describe a single bad request field. */
typedef struct _google_rpc_BadRequest_FieldViolation {
    /* A path that leads to a field in the request body. The value will be a
 sequence of dot-separated identifiers that identify a protocol buffer
 field.

 Consider the following:

     message CreateContactRequest {
       message EmailAddress {
         enum Type {
           TYPE_UNSPECIFIED = 0;
           HOME = 1;
           WORK = 2;
         }

         optional string email = 1;
         repeated EmailType type = 2;
       }

       string full_name = 1;
       repeated EmailAddress email_addresses = 2;
     }

 In this example, in proto `field` could take one of the following values:

 * `full_name` for a violation in the `full_name` value
 * `email_addresses[1].email` for a violation in the `email` field of the
   first `email_addresses` message
 * `email_addresses[3].type[2]` for a violation in the second `type`
   value in the third `email_addresses` message.

 In JSON, the same values are represented as:

 * `fullName` for a violation in the `fullName` value
 * `emailAddresses[1].email` for a violation in the `email` field of the
   first `emailAddresses` message
 * `emailAddresses[3].type[2]` for a violation in the second `type`
   value in the third `emailAddresses` message. */
    char field[1024];
    /* A description of why the request element is bad. */
    char description[1024];
    /* The reason of the field-level error. This is a constant value that
 identifies the proximate cause of the field-level error. It should
 uniquely identify the type of the FieldViolation within the scope of the
 google.rpc.ErrorInfo.domain. This should be at most 63
 characters and match a regular expression of `[A-Z][A-Z0-9_]+[A-Z0-9]`,
 which represents UPPER_SNAKE_CASE. */
    char reason[1024];
    /* Provides a localized error message for field-level errors that is safe to
 return to the API consumer. */
    bool has_localized_message;
    google_rpc_LocalizedMessage localized_message;
} google_rpc_BadRequest_FieldViolation;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define google_rpc_ErrorInfo_init_default        {"", "", {{NULL}, NULL}}
#define google_rpc_ErrorInfo_MetadataEntry_init_default {"", ""}
#define google_rpc_RetryInfo_init_default        {false, google_protobuf_Duration_init_default}
#define google_rpc_DebugInfo_init_default        {{{NULL}, NULL}, ""}
#define google_rpc_QuotaFailure_init_default     {{{NULL}, NULL}}
#define google_rpc_QuotaFailure_Violation_init_default {"", ""}
#define google_rpc_PreconditionFailure_init_default {{{NULL}, NULL}}
#define google_rpc_PreconditionFailure_Violation_init_default {"", "", ""}
#define google_rpc_BadRequest_init_default       {{{NULL}, NULL}}
#define google_rpc_BadRequest_FieldViolation_init_default {"", "", "", false, google_rpc_LocalizedMessage_init_default}
#define google_rpc_RequestInfo_init_default      {"", ""}
#define google_rpc_ResourceInfo_init_default     {"", "", "", ""}
#define google_rpc_Help_init_default             {{{NULL}, NULL}}
#define google_rpc_Help_Link_init_default        {"", ""}
#define google_rpc_LocalizedMessage_init_default {"", ""}
#define google_rpc_ErrorInfo_init_zero           {"", "", {{NULL}, NULL}}
#define google_rpc_ErrorInfo_MetadataEntry_init_zero {"", ""}
#define google_rpc_RetryInfo_init_zero           {false, google_protobuf_Duration_init_zero}
#define google_rpc_DebugInfo_init_zero           {{{NULL}, NULL}, ""}
#define google_rpc_QuotaFailure_init_zero        {{{NULL}, NULL}}
#define google_rpc_QuotaFailure_Violation_init_zero {"", ""}
#define google_rpc_PreconditionFailure_init_zero {{{NULL}, NULL}}
#define google_rpc_PreconditionFailure_Violation_init_zero {"", "", ""}
#define google_rpc_BadRequest_init_zero          {{{NULL}, NULL}}
#define google_rpc_BadRequest_FieldViolation_init_zero {"", "", "", false, google_rpc_LocalizedMessage_init_zero}
#define google_rpc_RequestInfo_init_zero         {"", ""}
#define google_rpc_ResourceInfo_init_zero        {"", "", "", ""}
#define google_rpc_Help_init_zero                {{{NULL}, NULL}}
#define google_rpc_Help_Link_init_zero           {"", ""}
#define google_rpc_LocalizedMessage_init_zero    {"", ""}

/* Field tags (for use in manual encoding/decoding) */
#define google_rpc_ErrorInfo_reason_tag          1
#define google_rpc_ErrorInfo_domain_tag          2
#define google_rpc_ErrorInfo_metadata_tag        3
#define google_rpc_ErrorInfo_MetadataEntry_key_tag 1
#define google_rpc_ErrorInfo_MetadataEntry_value_tag 2
#define google_rpc_RetryInfo_retry_delay_tag     1
#define google_rpc_DebugInfo_stack_entries_tag   1
#define google_rpc_DebugInfo_detail_tag          2
#define google_rpc_QuotaFailure_violations_tag   1
#define google_rpc_QuotaFailure_Violation_subject_tag 1
#define google_rpc_QuotaFailure_Violation_description_tag 2
#define google_rpc_PreconditionFailure_violations_tag 1
#define google_rpc_PreconditionFailure_Violation_type_tag 1
#define google_rpc_PreconditionFailure_Violation_subject_tag 2
#define google_rpc_PreconditionFailure_Violation_description_tag 3
#define google_rpc_BadRequest_field_violations_tag 1
#define google_rpc_RequestInfo_request_id_tag    1
#define google_rpc_RequestInfo_serving_data_tag  2
#define google_rpc_ResourceInfo_resource_type_tag 1
#define google_rpc_ResourceInfo_resource_name_tag 2
#define google_rpc_ResourceInfo_owner_tag        3
#define google_rpc_ResourceInfo_description_tag  4
#define google_rpc_Help_links_tag                1
#define google_rpc_Help_Link_description_tag     1
#define google_rpc_Help_Link_url_tag             2
#define google_rpc_LocalizedMessage_locale_tag   1
#define google_rpc_LocalizedMessage_message_tag  2
#define google_rpc_BadRequest_FieldViolation_field_tag 1
#define google_rpc_BadRequest_FieldViolation_description_tag 2
#define google_rpc_BadRequest_FieldViolation_reason_tag 3
#define google_rpc_BadRequest_FieldViolation_localized_message_tag 4

/* Struct field encoding specification for nanopb */
#define google_rpc_ErrorInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   reason,            1) \
X(a, STATIC,   SINGULAR, STRING,   domain,            2) \
X(a, CALLBACK, REPEATED, MESSAGE,  metadata,          3)
#define google_rpc_ErrorInfo_CALLBACK pb_default_field_callback
#define google_rpc_ErrorInfo_DEFAULT NULL
#define google_rpc_ErrorInfo_metadata_MSGTYPE google_rpc_ErrorInfo_MetadataEntry

#define google_rpc_ErrorInfo_MetadataEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2)
#define google_rpc_ErrorInfo_MetadataEntry_CALLBACK NULL
#define google_rpc_ErrorInfo_MetadataEntry_DEFAULT NULL

#define google_rpc_RetryInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  retry_delay,       1)
#define google_rpc_RetryInfo_CALLBACK NULL
#define google_rpc_RetryInfo_DEFAULT NULL
#define google_rpc_RetryInfo_retry_delay_MSGTYPE google_protobuf_Duration

#define google_rpc_DebugInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   stack_entries,     1) \
X(a, STATIC,   SINGULAR, STRING,   detail,            2)
#define google_rpc_DebugInfo_CALLBACK pb_default_field_callback
#define google_rpc_DebugInfo_DEFAULT NULL

#define google_rpc_QuotaFailure_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  violations,        1)
#define google_rpc_QuotaFailure_CALLBACK pb_default_field_callback
#define google_rpc_QuotaFailure_DEFAULT NULL
#define google_rpc_QuotaFailure_violations_MSGTYPE google_rpc_QuotaFailure_Violation

#define google_rpc_QuotaFailure_Violation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   subject,           1) \
X(a, STATIC,   SINGULAR, STRING,   description,       2)
#define google_rpc_QuotaFailure_Violation_CALLBACK NULL
#define google_rpc_QuotaFailure_Violation_DEFAULT NULL

#define google_rpc_PreconditionFailure_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  violations,        1)
#define google_rpc_PreconditionFailure_CALLBACK pb_default_field_callback
#define google_rpc_PreconditionFailure_DEFAULT NULL
#define google_rpc_PreconditionFailure_violations_MSGTYPE google_rpc_PreconditionFailure_Violation

#define google_rpc_PreconditionFailure_Violation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   type,              1) \
X(a, STATIC,   SINGULAR, STRING,   subject,           2) \
X(a, STATIC,   SINGULAR, STRING,   description,       3)
#define google_rpc_PreconditionFailure_Violation_CALLBACK NULL
#define google_rpc_PreconditionFailure_Violation_DEFAULT NULL

#define google_rpc_BadRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  field_violations,   1)
#define google_rpc_BadRequest_CALLBACK pb_default_field_callback
#define google_rpc_BadRequest_DEFAULT NULL
#define google_rpc_BadRequest_field_violations_MSGTYPE google_rpc_BadRequest_FieldViolation

#define google_rpc_BadRequest_FieldViolation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   field,             1) \
X(a, STATIC,   SINGULAR, STRING,   description,       2) \
X(a, STATIC,   SINGULAR, STRING,   reason,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  localized_message,   4)
#define google_rpc_BadRequest_FieldViolation_CALLBACK NULL
#define google_rpc_BadRequest_FieldViolation_DEFAULT NULL
#define google_rpc_BadRequest_FieldViolation_localized_message_MSGTYPE google_rpc_LocalizedMessage

#define google_rpc_RequestInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   request_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   serving_data,      2)
#define google_rpc_RequestInfo_CALLBACK NULL
#define google_rpc_RequestInfo_DEFAULT NULL

#define google_rpc_ResourceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   resource_type,     1) \
X(a, STATIC,   SINGULAR, STRING,   resource_name,     2) \
X(a, STATIC,   SINGULAR, STRING,   owner,             3) \
X(a, STATIC,   SINGULAR, STRING,   description,       4)
#define google_rpc_ResourceInfo_CALLBACK NULL
#define google_rpc_ResourceInfo_DEFAULT NULL

#define google_rpc_Help_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  links,             1)
#define google_rpc_Help_CALLBACK pb_default_field_callback
#define google_rpc_Help_DEFAULT NULL
#define google_rpc_Help_links_MSGTYPE google_rpc_Help_Link

#define google_rpc_Help_Link_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   description,       1) \
X(a, STATIC,   SINGULAR, STRING,   url,               2)
#define google_rpc_Help_Link_CALLBACK NULL
#define google_rpc_Help_Link_DEFAULT NULL

#define google_rpc_LocalizedMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   locale,            1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2)
#define google_rpc_LocalizedMessage_CALLBACK NULL
#define google_rpc_LocalizedMessage_DEFAULT NULL

extern const pb_msgdesc_t google_rpc_ErrorInfo_msg;
extern const pb_msgdesc_t google_rpc_ErrorInfo_MetadataEntry_msg;
extern const pb_msgdesc_t google_rpc_RetryInfo_msg;
extern const pb_msgdesc_t google_rpc_DebugInfo_msg;
extern const pb_msgdesc_t google_rpc_QuotaFailure_msg;
extern const pb_msgdesc_t google_rpc_QuotaFailure_Violation_msg;
extern const pb_msgdesc_t google_rpc_PreconditionFailure_msg;
extern const pb_msgdesc_t google_rpc_PreconditionFailure_Violation_msg;
extern const pb_msgdesc_t google_rpc_BadRequest_msg;
extern const pb_msgdesc_t google_rpc_BadRequest_FieldViolation_msg;
extern const pb_msgdesc_t google_rpc_RequestInfo_msg;
extern const pb_msgdesc_t google_rpc_ResourceInfo_msg;
extern const pb_msgdesc_t google_rpc_Help_msg;
extern const pb_msgdesc_t google_rpc_Help_Link_msg;
extern const pb_msgdesc_t google_rpc_LocalizedMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_rpc_ErrorInfo_fields &google_rpc_ErrorInfo_msg
#define google_rpc_ErrorInfo_MetadataEntry_fields &google_rpc_ErrorInfo_MetadataEntry_msg
#define google_rpc_RetryInfo_fields &google_rpc_RetryInfo_msg
#define google_rpc_DebugInfo_fields &google_rpc_DebugInfo_msg
#define google_rpc_QuotaFailure_fields &google_rpc_QuotaFailure_msg
#define google_rpc_QuotaFailure_Violation_fields &google_rpc_QuotaFailure_Violation_msg
#define google_rpc_PreconditionFailure_fields &google_rpc_PreconditionFailure_msg
#define google_rpc_PreconditionFailure_Violation_fields &google_rpc_PreconditionFailure_Violation_msg
#define google_rpc_BadRequest_fields &google_rpc_BadRequest_msg
#define google_rpc_BadRequest_FieldViolation_fields &google_rpc_BadRequest_FieldViolation_msg
#define google_rpc_RequestInfo_fields &google_rpc_RequestInfo_msg
#define google_rpc_ResourceInfo_fields &google_rpc_ResourceInfo_msg
#define google_rpc_Help_fields &google_rpc_Help_msg
#define google_rpc_Help_Link_fields &google_rpc_Help_Link_msg
#define google_rpc_LocalizedMessage_fields &google_rpc_LocalizedMessage_msg

/* Maximum encoded size of messages (where known) */
/* google_rpc_ErrorInfo_size depends on runtime parameters */
/* google_rpc_DebugInfo_size depends on runtime parameters */
/* google_rpc_QuotaFailure_size depends on runtime parameters */
/* google_rpc_PreconditionFailure_size depends on runtime parameters */
/* google_rpc_BadRequest_size depends on runtime parameters */
/* google_rpc_Help_size depends on runtime parameters */
#define GOOGLE_RPC_GOOGLE_RPC_ERROR_DETAILS_PB_H_MAX_SIZE google_rpc_BadRequest_FieldViolation_size
#define google_rpc_BadRequest_FieldViolation_size 5133
#define google_rpc_ErrorInfo_MetadataEntry_size  2052
#define google_rpc_Help_Link_size                2052
#define google_rpc_LocalizedMessage_size         2052
#define google_rpc_PreconditionFailure_Violation_size 3078
#define google_rpc_QuotaFailure_Violation_size   2052
#define google_rpc_RequestInfo_size              2052
#define google_rpc_ResourceInfo_size             4104
#define google_rpc_RetryInfo_size                24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
