/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GOOGLE_RPC_GOOGLE_RPC_STATUS_PB_H_INCLUDED
#define PB_GOOGLE_RPC_GOOGLE_RPC_STATUS_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/any.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* The `Status` type defines a logical error model that is suitable for
 different programming environments, including REST APIs and RPC APIs. It is
 used by [gRPC](https://github.com/grpc). Each `Status` message contains
 three pieces of data: error code, error message, and error details.

 You can find out more about this error model and how to work with it in the
 [API Design Guide](https://cloud.google.com/apis/design/errors). */
typedef struct _google_rpc_Status {
    /* The status code, which should be an enum value of
 [google.rpc.Code][google.rpc.Code]. */
    int32_t code;
    /* A developer-facing error message, which should be in English. Any
 user-facing error message should be localized and sent in the
 [google.rpc.Status.details][google.rpc.Status.details] field, or localized
 by the client. */
    char message[1024];
    /* A list of messages that carry the error details.  There is a common set of
 message types for APIs to use. */
    pb_callback_t details;
} google_rpc_Status;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define google_rpc_Status_init_default           {0, "", {{NULL}, NULL}}
#define google_rpc_Status_init_zero              {0, "", {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define google_rpc_Status_code_tag               1
#define google_rpc_Status_message_tag            2
#define google_rpc_Status_details_tag            3

/* Struct field encoding specification for nanopb */
#define google_rpc_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    code,              1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2) \
X(a, CALLBACK, REPEATED, MESSAGE,  details,           3)
#define google_rpc_Status_CALLBACK pb_default_field_callback
#define google_rpc_Status_DEFAULT NULL
#define google_rpc_Status_details_MSGTYPE google_protobuf_Any

extern const pb_msgdesc_t google_rpc_Status_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_rpc_Status_fields &google_rpc_Status_msg

/* Maximum encoded size of messages (where known) */
/* google_rpc_Status_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
