/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "google/rpc/status.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_rpc_Status, google_rpc_Status, 2)



