/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_DIGITALASSET_CANTON_PROTOCOL_V30_COM_DIGITALASSET_CANTON_PROTOCOL_V30_SEQUENCING_PARAMETERS_PB_H_INCLUDED
#define PB_COM_DIGITALASSET_CANTON_PROTOCOL_V30_COM_DIGITALASSET_CANTON_PROTOCOL_V30_SEQUENCING_PARAMETERS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_payload_t;
typedef struct _com_digitalasset_canton_protocol_v30_DynamicSequencingParameters {
    /* Sequencing dynamic synchronizer parameters can only be interpreted by a sequencer implementation
  and are opaque to the rest of the synchronizer. */
    com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_payload_t payload;
} com_digitalasset_canton_protocol_v30_DynamicSequencingParameters;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_init_default {{0, {0}}}
#define com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_init_zero {{0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_payload_tag 1

/* Struct field encoding specification for nanopb */
#define com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           1)
#define com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_CALLBACK NULL
#define com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_DEFAULT NULL

extern const pb_msgdesc_t com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_fields &com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_msg

/* Maximum encoded size of messages (where known) */
#define COM_DIGITALASSET_CANTON_PROTOCOL_V30_COM_DIGITALASSET_CANTON_PROTOCOL_V30_SEQUENCING_PARAMETERS_PB_H_MAX_SIZE com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_size
#define com_digitalasset_canton_protocol_v30_DynamicSequencingParameters_size 1027

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
