/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com/digitalasset/canton/protocol/v30/sequencing_parameters.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_digitalasset_canton_protocol_v30_DynamicSequencingParameters, com_digitalasset_canton_protocol_v30_DynamicSequencingParameters, 2)



