/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_DIGITALASSET_CANTON_PROTOCOL_V30_COM_DIGITALASSET_CANTON_PROTOCOL_V30_TRAFFIC_CONTROL_PARAMETERS_PB_H_INCLUDED
#define PB_COM_DIGITALASSET_CANTON_PROTOCOL_V30_COM_DIGITALASSET_CANTON_PROTOCOL_V30_TRAFFIC_CONTROL_PARAMETERS_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/duration.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _com_digitalasset_canton_protocol_v30_TrafficControlParameters {
    /* [doc-entry-start: TrafficControlParameters]
 In bytes, the maximum amount of base traffic that can be accumulated */
    uint64_t max_base_traffic_amount;
    /* Maximum duration over which the base rate can be accumulated
 Consequently, base_traffic_rate = max_base_traffic_amount / max_base_traffic_accumulation_duration */
    bool has_max_base_traffic_accumulation_duration;
    google_protobuf_Duration max_base_traffic_accumulation_duration;
    /* Read scaling factor to compute the event cost. In parts per 10 000. */
    uint32_t read_vs_write_scaling_factor;
    /* Window size used to compute the max sequencing time of a submission request
 This impacts how quickly a submission is expected to be accepted before a retry should be attempted by the caller
 Default is 5 minutes */
    bool has_set_balance_request_submission_window_size;
    google_protobuf_Duration set_balance_request_submission_window_size;
    /* If true, submission requests without enough traffic credit will not be delivered */
    bool enforce_rate_limiting;
    /* In bytes, base event cost added to all sequenced events.
 Optional */
    bool has_base_event_cost;
    uint64_t base_event_cost;
    /* Whether to charge for confirmation responses
 Default: false */
    bool free_confirmation_responses; /* [doc-entry-end: TrafficControlParameters] */
} com_digitalasset_canton_protocol_v30_TrafficControlParameters;

/* Message representing a traffic receipt included in SequencedEvent receipts to update sender about
 the traffic consumed state after sequencing of the event */
typedef struct _com_digitalasset_canton_protocol_v30_TrafficReceipt {
    /* Cost effectively consumed by this specific event */
    uint64_t consumed_cost;
    /* Total amount of extra traffic consumed */
    uint64_t extra_traffic_consumed;
    /* Remaining free base traffic */
    uint64_t base_traffic_remainder;
} com_digitalasset_canton_protocol_v30_TrafficReceipt;

/* Message representing traffic consumed by a member at a given point in time */
typedef struct _com_digitalasset_canton_protocol_v30_TrafficConsumed {
    /* Member consuming the traffic */
    char member[1024];
    /* Total extra traffic consumed */
    uint64_t extra_traffic_consumed;
    /* Remaining free base traffic */
    uint64_t base_traffic_remainder;
    /* Cost deducted at `timestamp`, only present when traffic was consumed at `timestamp`, otherwise is set to 0 */
    uint64_t last_consumed_cost;
    /* Timestamp at which this state is valid - this timestamp is used to compute the base traffic remainder above */
    int64_t sequencing_timestamp; /* in microseconds of UTC time since Unix epoch */
} com_digitalasset_canton_protocol_v30_TrafficConsumed;

/* Message representing a traffic purchase made on behalf of a member */
typedef struct _com_digitalasset_canton_protocol_v30_TrafficPurchased {
    /* Member receiving the traffic */
    char member[1024];
    /* Serial of the update */
    uint32_t serial;
    /* New total extra traffic purchased */
    uint64_t extra_traffic_purchased;
    /* Timestamp at which this state is valid */
    int64_t sequencing_timestamp; /* // in microseconds of UTC time since Unix epoch */
} com_digitalasset_canton_protocol_v30_TrafficPurchased;

/* Traffic state of a member at a given timestamp */
typedef struct _com_digitalasset_canton_protocol_v30_TrafficState {
    /* Total amount of extra traffic purchased */
    int64_t extra_traffic_purchased;
    /* Total amount of extra traffic consumed */
    int64_t extra_traffic_consumed;
    /* Amount of base traffic remaining */
    int64_t base_traffic_remainder;
    /* Cost deducted at `timestamp`, only present when traffic was consumed at `timestamp`, otherwise is set to 0 */
    uint64_t last_consumed_cost;
    /* Timestamp at which the state is valid */
    int64_t timestamp;
    /* Optional serial of the balance update that updated the extra traffic limit */
    bool has_serial;
    uint32_t serial;
} com_digitalasset_canton_protocol_v30_TrafficState;

typedef struct _com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage {
    /* Member to update the balance for */
    char member[1024];
    /* Serial number - must be unique and monotonically increasing for each new purchase update */
    uint32_t serial;
    /* New total traffic purchased entry */
    uint64_t total_traffic_purchased;
    char physical_synchronizer_id[1024];
} com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_init_default {0, false, google_protobuf_Duration_init_default, 0, false, google_protobuf_Duration_init_default, 0, false, 0, 0}
#define com_digitalasset_canton_protocol_v30_TrafficReceipt_init_default {0, 0, 0}
#define com_digitalasset_canton_protocol_v30_TrafficConsumed_init_default {"", 0, 0, 0, 0}
#define com_digitalasset_canton_protocol_v30_TrafficPurchased_init_default {"", 0, 0, 0}
#define com_digitalasset_canton_protocol_v30_TrafficState_init_default {0, 0, 0, 0, 0, false, 0}
#define com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_init_default {"", 0, 0, ""}
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_init_zero {0, false, google_protobuf_Duration_init_zero, 0, false, google_protobuf_Duration_init_zero, 0, false, 0, 0}
#define com_digitalasset_canton_protocol_v30_TrafficReceipt_init_zero {0, 0, 0}
#define com_digitalasset_canton_protocol_v30_TrafficConsumed_init_zero {"", 0, 0, 0, 0}
#define com_digitalasset_canton_protocol_v30_TrafficPurchased_init_zero {"", 0, 0, 0}
#define com_digitalasset_canton_protocol_v30_TrafficState_init_zero {0, 0, 0, 0, 0, false, 0}
#define com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_init_zero {"", 0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_max_base_traffic_amount_tag 1
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_max_base_traffic_accumulation_duration_tag 3
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_read_vs_write_scaling_factor_tag 4
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_set_balance_request_submission_window_size_tag 5
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_enforce_rate_limiting_tag 6
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_base_event_cost_tag 7
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_free_confirmation_responses_tag 8
#define com_digitalasset_canton_protocol_v30_TrafficReceipt_consumed_cost_tag 1
#define com_digitalasset_canton_protocol_v30_TrafficReceipt_extra_traffic_consumed_tag 2
#define com_digitalasset_canton_protocol_v30_TrafficReceipt_base_traffic_remainder_tag 3
#define com_digitalasset_canton_protocol_v30_TrafficConsumed_member_tag 1
#define com_digitalasset_canton_protocol_v30_TrafficConsumed_extra_traffic_consumed_tag 2
#define com_digitalasset_canton_protocol_v30_TrafficConsumed_base_traffic_remainder_tag 3
#define com_digitalasset_canton_protocol_v30_TrafficConsumed_last_consumed_cost_tag 4
#define com_digitalasset_canton_protocol_v30_TrafficConsumed_sequencing_timestamp_tag 5
#define com_digitalasset_canton_protocol_v30_TrafficPurchased_member_tag 1
#define com_digitalasset_canton_protocol_v30_TrafficPurchased_serial_tag 2
#define com_digitalasset_canton_protocol_v30_TrafficPurchased_extra_traffic_purchased_tag 3
#define com_digitalasset_canton_protocol_v30_TrafficPurchased_sequencing_timestamp_tag 4
#define com_digitalasset_canton_protocol_v30_TrafficState_extra_traffic_purchased_tag 1
#define com_digitalasset_canton_protocol_v30_TrafficState_extra_traffic_consumed_tag 2
#define com_digitalasset_canton_protocol_v30_TrafficState_base_traffic_remainder_tag 3
#define com_digitalasset_canton_protocol_v30_TrafficState_last_consumed_cost_tag 4
#define com_digitalasset_canton_protocol_v30_TrafficState_timestamp_tag 5
#define com_digitalasset_canton_protocol_v30_TrafficState_serial_tag 6
#define com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_member_tag 1
#define com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_serial_tag 2
#define com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_total_traffic_purchased_tag 4
#define com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_physical_synchronizer_id_tag 5

/* Struct field encoding specification for nanopb */
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   max_base_traffic_amount,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  max_base_traffic_accumulation_duration,   3) \
X(a, STATIC,   SINGULAR, UINT32,   read_vs_write_scaling_factor,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  set_balance_request_submission_window_size,   5) \
X(a, STATIC,   SINGULAR, BOOL,     enforce_rate_limiting,   6) \
X(a, STATIC,   OPTIONAL, UINT64,   base_event_cost,   7) \
X(a, STATIC,   SINGULAR, BOOL,     free_confirmation_responses,   8)
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_CALLBACK NULL
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_DEFAULT NULL
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_max_base_traffic_accumulation_duration_MSGTYPE google_protobuf_Duration
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_set_balance_request_submission_window_size_MSGTYPE google_protobuf_Duration

#define com_digitalasset_canton_protocol_v30_TrafficReceipt_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   consumed_cost,     1) \
X(a, STATIC,   SINGULAR, UINT64,   extra_traffic_consumed,   2) \
X(a, STATIC,   SINGULAR, UINT64,   base_traffic_remainder,   3)
#define com_digitalasset_canton_protocol_v30_TrafficReceipt_CALLBACK NULL
#define com_digitalasset_canton_protocol_v30_TrafficReceipt_DEFAULT NULL

#define com_digitalasset_canton_protocol_v30_TrafficConsumed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   member,            1) \
X(a, STATIC,   SINGULAR, UINT64,   extra_traffic_consumed,   2) \
X(a, STATIC,   SINGULAR, UINT64,   base_traffic_remainder,   3) \
X(a, STATIC,   SINGULAR, UINT64,   last_consumed_cost,   4) \
X(a, STATIC,   SINGULAR, INT64,    sequencing_timestamp,   5)
#define com_digitalasset_canton_protocol_v30_TrafficConsumed_CALLBACK NULL
#define com_digitalasset_canton_protocol_v30_TrafficConsumed_DEFAULT NULL

#define com_digitalasset_canton_protocol_v30_TrafficPurchased_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   member,            1) \
X(a, STATIC,   SINGULAR, UINT32,   serial,            2) \
X(a, STATIC,   SINGULAR, UINT64,   extra_traffic_purchased,   3) \
X(a, STATIC,   SINGULAR, INT64,    sequencing_timestamp,   4)
#define com_digitalasset_canton_protocol_v30_TrafficPurchased_CALLBACK NULL
#define com_digitalasset_canton_protocol_v30_TrafficPurchased_DEFAULT NULL

#define com_digitalasset_canton_protocol_v30_TrafficState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    extra_traffic_purchased,   1) \
X(a, STATIC,   SINGULAR, INT64,    extra_traffic_consumed,   2) \
X(a, STATIC,   SINGULAR, INT64,    base_traffic_remainder,   3) \
X(a, STATIC,   SINGULAR, UINT64,   last_consumed_cost,   4) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         5) \
X(a, STATIC,   OPTIONAL, UINT32,   serial,            6)
#define com_digitalasset_canton_protocol_v30_TrafficState_CALLBACK NULL
#define com_digitalasset_canton_protocol_v30_TrafficState_DEFAULT NULL

#define com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   member,            1) \
X(a, STATIC,   SINGULAR, UINT32,   serial,            2) \
X(a, STATIC,   SINGULAR, UINT64,   total_traffic_purchased,   4) \
X(a, STATIC,   SINGULAR, STRING,   physical_synchronizer_id,   5)
#define com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_CALLBACK NULL
#define com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_DEFAULT NULL

extern const pb_msgdesc_t com_digitalasset_canton_protocol_v30_TrafficControlParameters_msg;
extern const pb_msgdesc_t com_digitalasset_canton_protocol_v30_TrafficReceipt_msg;
extern const pb_msgdesc_t com_digitalasset_canton_protocol_v30_TrafficConsumed_msg;
extern const pb_msgdesc_t com_digitalasset_canton_protocol_v30_TrafficPurchased_msg;
extern const pb_msgdesc_t com_digitalasset_canton_protocol_v30_TrafficState_msg;
extern const pb_msgdesc_t com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_fields &com_digitalasset_canton_protocol_v30_TrafficControlParameters_msg
#define com_digitalasset_canton_protocol_v30_TrafficReceipt_fields &com_digitalasset_canton_protocol_v30_TrafficReceipt_msg
#define com_digitalasset_canton_protocol_v30_TrafficConsumed_fields &com_digitalasset_canton_protocol_v30_TrafficConsumed_msg
#define com_digitalasset_canton_protocol_v30_TrafficPurchased_fields &com_digitalasset_canton_protocol_v30_TrafficPurchased_msg
#define com_digitalasset_canton_protocol_v30_TrafficState_fields &com_digitalasset_canton_protocol_v30_TrafficState_msg
#define com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_fields &com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_msg

/* Maximum encoded size of messages (where known) */
#define COM_DIGITALASSET_CANTON_PROTOCOL_V30_COM_DIGITALASSET_CANTON_PROTOCOL_V30_TRAFFIC_CONTROL_PARAMETERS_PB_H_MAX_SIZE com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_size
#define com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage_size 2069
#define com_digitalasset_canton_protocol_v30_TrafficConsumed_size 1070
#define com_digitalasset_canton_protocol_v30_TrafficControlParameters_size 80
#define com_digitalasset_canton_protocol_v30_TrafficPurchased_size 1054
#define com_digitalasset_canton_protocol_v30_TrafficReceipt_size 33
#define com_digitalasset_canton_protocol_v30_TrafficState_size 61

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
