/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com/digitalasset/canton/protocol/v30/traffic_control_parameters.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_digitalasset_canton_protocol_v30_TrafficControlParameters, com_digitalasset_canton_protocol_v30_TrafficControlParameters, AUTO)


PB_BIND(com_digitalasset_canton_protocol_v30_TrafficReceipt, com_digitalasset_canton_protocol_v30_TrafficReceipt, AUTO)


PB_BIND(com_digitalasset_canton_protocol_v30_TrafficConsumed, com_digitalasset_canton_protocol_v30_TrafficConsumed, 2)


PB_BIND(com_digitalasset_canton_protocol_v30_TrafficPurchased, com_digitalasset_canton_protocol_v30_TrafficPurchased, 2)


PB_BIND(com_digitalasset_canton_protocol_v30_TrafficState, com_digitalasset_canton_protocol_v30_TrafficState, AUTO)


PB_BIND(com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage, com_digitalasset_canton_protocol_v30_SetTrafficPurchasedMessage, 2)



