/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com/daml/ledger/api/v2/commands.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_daml_ledger_api_v2_Command, com_daml_ledger_api_v2_Command, 4)


PB_BIND(com_daml_ledger_api_v2_CreateCommand, com_daml_ledger_api_v2_CreateCommand, 2)


PB_BIND(com_daml_ledger_api_v2_ExerciseCommand, com_daml_ledger_api_v2_ExerciseCommand, 4)


PB_BIND(com_daml_ledger_api_v2_ExerciseByKeyCommand, com_daml_ledger_api_v2_ExerciseByKeyCommand, 4)


PB_BIND(com_daml_ledger_api_v2_CreateAndExerciseCommand, com_daml_ledger_api_v2_CreateAndExerciseCommand, 4)


PB_BIND(com_daml_ledger_api_v2_DisclosedContract, com_daml_ledger_api_v2_DisclosedContract, 2)


PB_BIND(com_daml_ledger_api_v2_Commands, com_daml_ledger_api_v2_Commands, 2)


PB_BIND(com_daml_ledger_api_v2_PrefetchContractKey, com_daml_ledger_api_v2_PrefetchContractKey, 4)



