/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_COMPLETION_PB_H_INCLUDED
#define PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_COMPLETION_PB_H_INCLUDED
#include <pb.h>
#include "com/daml/ledger/api/v2/offset_checkpoint.pb.h"
#include "com/daml/ledger/api/v2/trace_context.pb.h"
#include "google/protobuf/duration.pb.h"
#include "google/rpc/status.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* A completion represents the status of a submitted command on the ledger: it can be successful or failed. */
typedef struct _com_daml_ledger_api_v2_Completion {
    /* The ID of the succeeded or failed command.
 Must be a valid LedgerString (as described in ``value.proto``).

 Required */
    char command_id[1024];
    /* Identifies the exact type of the error.
 It uses the same format of conveying error details as it is used for the RPC responses of the APIs.

 Optional */
    bool has_status;
    google_rpc_Status status;
    /* The update_id of the transaction or reassignment that resulted from the command with command_id.

 Only set for successfully executed commands.
 Must be a valid LedgerString (as described in ``value.proto``).

 Optional */
    char update_id[1024];
    /* The user-id that was used for the submission, as described in ``commands.proto``.
 Must be a valid UserIdString (as described in ``value.proto``).

 Required */
    char user_id[1024];
    /* The set of parties on whose behalf the commands were executed.
 Contains the ``act_as`` parties from ``commands.proto``
 filtered to the requesting parties in CompletionStreamRequest.
 The order of the parties need not be the same as in the submission.
 Each element must be a valid PartyIdString (as described in ``value.proto``).

 Required: must be non-empty */
    pb_callback_t act_as;
    /* The submission ID this completion refers to, as described in ``commands.proto``.
 Must be a valid LedgerString (as described in ``value.proto``).

 Optional */
    char submission_id[1024];
    pb_size_t which_deduplication_period;
    union {
        /* Specifies the start of the deduplication period by a completion stream offset (exclusive).
    
     Must be a valid absolute offset (positive integer) or participant begin (zero). */
        int64_t deduplication_offset;
        /* Specifies the length of the deduplication period.
     It is measured in record time of completions.
    
     Must be non-negative. */
        google_protobuf_Duration deduplication_duration;
    } deduplication_period;
    /* The Ledger API trace context

 The trace context transported in this message corresponds to the trace context supplied
 by the client application in a HTTP2 header of the original command submission.
 We typically use a header to transfer this type of information. Here we use message
 body, because it is used in gRPC streams which do not support per message headers.
 This field will be populated with the trace context contained in the original submission.
 If that was not provided, a unique ledger-api-server generated trace context will be used
 instead.

 Optional */
    bool has_trace_context;
    com_daml_ledger_api_v2_TraceContext trace_context;
    /* May be used in a subsequent CompletionStreamRequest to resume the consumption of this stream at a later time.
 Must be a valid absolute offset (positive integer).

 Required */
    int64_t offset;
    /* The synchronizer along with its record time.
 The synchronizer id provided, in case of

 - successful/failed transactions: identifies the synchronizer of the transaction
 - for successful/failed unassign commands: identifies the source synchronizer
 - for successful/failed assign commands: identifies the target synchronizer

 Required */
    bool has_synchronizer_time;
    com_daml_ledger_api_v2_SynchronizerTime synchronizer_time;
    /* The traffic cost paid by this participant node for the confirmation request
 for the submitted command.

 Commands whose execution is rejected before their corresponding
 confirmation request is ordered by the synchronizer will report a paid
 traffic cost of zero.
 If a confirmation request is ordered for a command, but the request fails
 (e.g., due to contention with a concurrent contract archival), the traffic
 cost is paid and reported on the failed completion for the request.

 If you want to correlate the traffic cost of a successful completion
 with the transaction that resulted from the command, you can use the
 ``offset`` field to retrieve the transaction using
 ``UpdateService.GetUpdateByOffset`` on the same participant node; or alternatively use the ``update_id``
 field to retrieve the transaction using ``UpdateService.GetUpdateById`` on any participant node
 that sees the transaction.

 Note: for completions processed before the participant started serving
 traffic cost on the Ledger API, this field will be set to zero.
 Additionally, the total cost incurred by the submitting node for the submission of the transaction may be greater
 than the reported cost, for example if retries were issued due to failed submissions to the synchronizer.
 The cost reported here is the one paid for ordering the confirmation request.

 Optional */
    int64_t paid_traffic_cost;
} com_daml_ledger_api_v2_Completion;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define com_daml_ledger_api_v2_Completion_init_default {"", false, google_rpc_Status_init_default, "", "", {{NULL}, NULL}, "", 0, {0}, false, com_daml_ledger_api_v2_TraceContext_init_default, 0, false, com_daml_ledger_api_v2_SynchronizerTime_init_default, 0}
#define com_daml_ledger_api_v2_Completion_init_zero {"", false, google_rpc_Status_init_zero, "", "", {{NULL}, NULL}, "", 0, {0}, false, com_daml_ledger_api_v2_TraceContext_init_zero, 0, false, com_daml_ledger_api_v2_SynchronizerTime_init_zero, 0}

/* Field tags (for use in manual encoding/decoding) */
#define com_daml_ledger_api_v2_Completion_command_id_tag 1
#define com_daml_ledger_api_v2_Completion_status_tag 2
#define com_daml_ledger_api_v2_Completion_update_id_tag 3
#define com_daml_ledger_api_v2_Completion_user_id_tag 4
#define com_daml_ledger_api_v2_Completion_act_as_tag 5
#define com_daml_ledger_api_v2_Completion_submission_id_tag 6
#define com_daml_ledger_api_v2_Completion_deduplication_offset_tag 7
#define com_daml_ledger_api_v2_Completion_deduplication_duration_tag 8
#define com_daml_ledger_api_v2_Completion_trace_context_tag 9
#define com_daml_ledger_api_v2_Completion_offset_tag 10
#define com_daml_ledger_api_v2_Completion_synchronizer_time_tag 11
#define com_daml_ledger_api_v2_Completion_paid_traffic_cost_tag 12

/* Struct field encoding specification for nanopb */
#define com_daml_ledger_api_v2_Completion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   command_id,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            2) \
X(a, STATIC,   SINGULAR, STRING,   update_id,         3) \
X(a, STATIC,   SINGULAR, STRING,   user_id,           4) \
X(a, CALLBACK, REPEATED, STRING,   act_as,            5) \
X(a, STATIC,   SINGULAR, STRING,   submission_id,     6) \
X(a, STATIC,   ONEOF,    INT64,    (deduplication_period,deduplication_offset,deduplication_period.deduplication_offset),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (deduplication_period,deduplication_duration,deduplication_period.deduplication_duration),   8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  trace_context,     9) \
X(a, STATIC,   SINGULAR, INT64,    offset,           10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  synchronizer_time,  11) \
X(a, STATIC,   SINGULAR, INT64,    paid_traffic_cost,  12)
#define com_daml_ledger_api_v2_Completion_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_Completion_DEFAULT NULL
#define com_daml_ledger_api_v2_Completion_status_MSGTYPE google_rpc_Status
#define com_daml_ledger_api_v2_Completion_deduplication_period_deduplication_duration_MSGTYPE google_protobuf_Duration
#define com_daml_ledger_api_v2_Completion_trace_context_MSGTYPE com_daml_ledger_api_v2_TraceContext
#define com_daml_ledger_api_v2_Completion_synchronizer_time_MSGTYPE com_daml_ledger_api_v2_SynchronizerTime

extern const pb_msgdesc_t com_daml_ledger_api_v2_Completion_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_daml_ledger_api_v2_Completion_fields &com_daml_ledger_api_v2_Completion_msg

/* Maximum encoded size of messages (where known) */
/* com_daml_ledger_api_v2_Completion_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
