/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com/daml/ledger/api/v2/crypto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_daml_ledger_api_v2_SigningPublicKey, com_daml_ledger_api_v2_SigningPublicKey, 2)


PB_BIND(com_daml_ledger_api_v2_Signature, com_daml_ledger_api_v2_Signature, 2)











