/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_CRYPTO_PB_H_INCLUDED
#define PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_CRYPTO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _com_daml_ledger_api_v2_SigningKeySpec {
    com_daml_ledger_api_v2_SigningKeySpec_SIGNING_KEY_SPEC_UNSPECIFIED = 0,
    /* Elliptic Curve Key from Curve25519
 as defined in http://ed25519.cr.yp.to/ */
    com_daml_ledger_api_v2_SigningKeySpec_SIGNING_KEY_SPEC_EC_CURVE25519 = 1,
    /* Elliptic Curve Key from the NIST P-256 curve (aka secp256r1)
 as defined in https://doi.org/10.6028/NIST.FIPS.186-4 */
    com_daml_ledger_api_v2_SigningKeySpec_SIGNING_KEY_SPEC_EC_P256 = 2,
    /* Elliptic Curve Key from the NIST P-384 curve (aka secp384r1)
 as defined in https://doi.org/10.6028/NIST.FIPS.186-4 */
    com_daml_ledger_api_v2_SigningKeySpec_SIGNING_KEY_SPEC_EC_P384 = 3,
    /* Elliptic Curve Key from SECG P256k1 curve (aka secp256k1)
 commonly used in bitcoin and ethereum
 as defined in https://www.secg.org/sec2-v2.pdf */
    com_daml_ledger_api_v2_SigningKeySpec_SIGNING_KEY_SPEC_EC_SECP256K1 = 4
} com_daml_ledger_api_v2_SigningKeySpec;

/* Serialization format for crypto keys and signatures */
typedef enum _com_daml_ledger_api_v2_CryptoKeyFormat {
    com_daml_ledger_api_v2_CryptoKeyFormat_CRYPTO_KEY_FORMAT_UNSPECIFIED = 0,
    /* ASN.1 + DER encoding
 Legacy format no longer used, except for migrations */
    com_daml_ledger_api_v2_CryptoKeyFormat_CRYPTO_KEY_FORMAT_DER = 1,
    /* Raw encoding of a key */
    com_daml_ledger_api_v2_CryptoKeyFormat_CRYPTO_KEY_FORMAT_RAW = 2,
    /* ASN.1 + DER-encoding of X.509 SubjectPublicKeyInfo structure: https://datatracker.ietf.org/doc/html/rfc5280#section-4.1 */
    com_daml_ledger_api_v2_CryptoKeyFormat_CRYPTO_KEY_FORMAT_DER_X509_SUBJECT_PUBLIC_KEY_INFO = 3
} com_daml_ledger_api_v2_CryptoKeyFormat;

typedef enum _com_daml_ledger_api_v2_SigningAlgorithmSpec {
    com_daml_ledger_api_v2_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_UNSPECIFIED = 0,
    /* EdDSA Signature based on Curve25519 with SHA-512
 http://ed25519.cr.yp.to/ */
    com_daml_ledger_api_v2_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_ED25519 = 1,
    /* Elliptic Curve Digital Signature Algorithm with SHA256 */
    com_daml_ledger_api_v2_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_256 = 2,
    /* Elliptic Curve Digital Signature Algorithm with SHA384 */
    com_daml_ledger_api_v2_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384 = 3
} com_daml_ledger_api_v2_SigningAlgorithmSpec;

typedef enum _com_daml_ledger_api_v2_SignatureFormat {
    com_daml_ledger_api_v2_SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED = 0,
    /* Signature scheme specific signature format
 Legacy format no longer used, except for migrations */
    com_daml_ledger_api_v2_SignatureFormat_SIGNATURE_FORMAT_RAW = 1,
    /* ASN.1 + DER-encoding of the `r` and `s` integers, as defined in https://datatracker.ietf.org/doc/html/rfc3279#section-2.2.3
 Used for ECDSA signatures */
    com_daml_ledger_api_v2_SignatureFormat_SIGNATURE_FORMAT_DER = 2,
    /* Concatenation of the integers `r || s` in little-endian form, as defined in https://datatracker.ietf.org/doc/html/rfc8032#section-3.3
 Note that this is different from the format defined in IEEE P1363, which uses concatenation in big-endian form.
 Used for EdDSA signatures */
    com_daml_ledger_api_v2_SignatureFormat_SIGNATURE_FORMAT_CONCAT = 3,
    /* Symbolic crypto, must only be used for testing */
    com_daml_ledger_api_v2_SignatureFormat_SIGNATURE_FORMAT_SYMBOLIC = 10000
} com_daml_ledger_api_v2_SignatureFormat;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1024) com_daml_ledger_api_v2_SigningPublicKey_key_data_t;
typedef struct _com_daml_ledger_api_v2_SigningPublicKey {
    /* The serialization format of the public key */
    com_daml_ledger_api_v2_CryptoKeyFormat format;
    /* Serialized public key in the format specified above */
    com_daml_ledger_api_v2_SigningPublicKey_key_data_t key_data;
    /* The key specification */
    com_daml_ledger_api_v2_SigningKeySpec key_spec;
} com_daml_ledger_api_v2_SigningPublicKey;

typedef PB_BYTES_ARRAY_T(1024) com_daml_ledger_api_v2_Signature_signature_t;
typedef struct _com_daml_ledger_api_v2_Signature {
    com_daml_ledger_api_v2_SignatureFormat format;
    com_daml_ledger_api_v2_Signature_signature_t signature;
    /* The fingerprint/id of the keypair used to create this signature and needed to verify. */
    char signed_by[1024];
    /* The signing algorithm specification used to produce this signature */
    com_daml_ledger_api_v2_SigningAlgorithmSpec signing_algorithm_spec;
} com_daml_ledger_api_v2_Signature;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _com_daml_ledger_api_v2_SigningKeySpec_MIN com_daml_ledger_api_v2_SigningKeySpec_SIGNING_KEY_SPEC_UNSPECIFIED
#define _com_daml_ledger_api_v2_SigningKeySpec_MAX com_daml_ledger_api_v2_SigningKeySpec_SIGNING_KEY_SPEC_EC_SECP256K1
#define _com_daml_ledger_api_v2_SigningKeySpec_ARRAYSIZE ((com_daml_ledger_api_v2_SigningKeySpec)(com_daml_ledger_api_v2_SigningKeySpec_SIGNING_KEY_SPEC_EC_SECP256K1+1))

#define _com_daml_ledger_api_v2_CryptoKeyFormat_MIN com_daml_ledger_api_v2_CryptoKeyFormat_CRYPTO_KEY_FORMAT_UNSPECIFIED
#define _com_daml_ledger_api_v2_CryptoKeyFormat_MAX com_daml_ledger_api_v2_CryptoKeyFormat_CRYPTO_KEY_FORMAT_DER_X509_SUBJECT_PUBLIC_KEY_INFO
#define _com_daml_ledger_api_v2_CryptoKeyFormat_ARRAYSIZE ((com_daml_ledger_api_v2_CryptoKeyFormat)(com_daml_ledger_api_v2_CryptoKeyFormat_CRYPTO_KEY_FORMAT_DER_X509_SUBJECT_PUBLIC_KEY_INFO+1))

#define _com_daml_ledger_api_v2_SigningAlgorithmSpec_MIN com_daml_ledger_api_v2_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_UNSPECIFIED
#define _com_daml_ledger_api_v2_SigningAlgorithmSpec_MAX com_daml_ledger_api_v2_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384
#define _com_daml_ledger_api_v2_SigningAlgorithmSpec_ARRAYSIZE ((com_daml_ledger_api_v2_SigningAlgorithmSpec)(com_daml_ledger_api_v2_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384+1))

#define _com_daml_ledger_api_v2_SignatureFormat_MIN com_daml_ledger_api_v2_SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED
#define _com_daml_ledger_api_v2_SignatureFormat_MAX com_daml_ledger_api_v2_SignatureFormat_SIGNATURE_FORMAT_SYMBOLIC
#define _com_daml_ledger_api_v2_SignatureFormat_ARRAYSIZE ((com_daml_ledger_api_v2_SignatureFormat)(com_daml_ledger_api_v2_SignatureFormat_SIGNATURE_FORMAT_SYMBOLIC+1))

#define com_daml_ledger_api_v2_SigningPublicKey_format_ENUMTYPE com_daml_ledger_api_v2_CryptoKeyFormat
#define com_daml_ledger_api_v2_SigningPublicKey_key_spec_ENUMTYPE com_daml_ledger_api_v2_SigningKeySpec

#define com_daml_ledger_api_v2_Signature_format_ENUMTYPE com_daml_ledger_api_v2_SignatureFormat
#define com_daml_ledger_api_v2_Signature_signing_algorithm_spec_ENUMTYPE com_daml_ledger_api_v2_SigningAlgorithmSpec


/* Initializer values for message structs */
#define com_daml_ledger_api_v2_SigningPublicKey_init_default {_com_daml_ledger_api_v2_CryptoKeyFormat_MIN, {0, {0}}, _com_daml_ledger_api_v2_SigningKeySpec_MIN}
#define com_daml_ledger_api_v2_Signature_init_default {_com_daml_ledger_api_v2_SignatureFormat_MIN, {0, {0}}, "", _com_daml_ledger_api_v2_SigningAlgorithmSpec_MIN}
#define com_daml_ledger_api_v2_SigningPublicKey_init_zero {_com_daml_ledger_api_v2_CryptoKeyFormat_MIN, {0, {0}}, _com_daml_ledger_api_v2_SigningKeySpec_MIN}
#define com_daml_ledger_api_v2_Signature_init_zero {_com_daml_ledger_api_v2_SignatureFormat_MIN, {0, {0}}, "", _com_daml_ledger_api_v2_SigningAlgorithmSpec_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define com_daml_ledger_api_v2_SigningPublicKey_format_tag 1
#define com_daml_ledger_api_v2_SigningPublicKey_key_data_tag 2
#define com_daml_ledger_api_v2_SigningPublicKey_key_spec_tag 3
#define com_daml_ledger_api_v2_Signature_format_tag 1
#define com_daml_ledger_api_v2_Signature_signature_tag 2
#define com_daml_ledger_api_v2_Signature_signed_by_tag 3
#define com_daml_ledger_api_v2_Signature_signing_algorithm_spec_tag 4

/* Struct field encoding specification for nanopb */
#define com_daml_ledger_api_v2_SigningPublicKey_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    format,            1) \
X(a, STATIC,   SINGULAR, BYTES,    key_data,          2) \
X(a, STATIC,   SINGULAR, UENUM,    key_spec,          3)
#define com_daml_ledger_api_v2_SigningPublicKey_CALLBACK NULL
#define com_daml_ledger_api_v2_SigningPublicKey_DEFAULT NULL

#define com_daml_ledger_api_v2_Signature_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    format,            1) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         2) \
X(a, STATIC,   SINGULAR, STRING,   signed_by,         3) \
X(a, STATIC,   SINGULAR, UENUM,    signing_algorithm_spec,   4)
#define com_daml_ledger_api_v2_Signature_CALLBACK NULL
#define com_daml_ledger_api_v2_Signature_DEFAULT NULL

extern const pb_msgdesc_t com_daml_ledger_api_v2_SigningPublicKey_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_Signature_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_daml_ledger_api_v2_SigningPublicKey_fields &com_daml_ledger_api_v2_SigningPublicKey_msg
#define com_daml_ledger_api_v2_Signature_fields &com_daml_ledger_api_v2_Signature_msg

/* Maximum encoded size of messages (where known) */
#define COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_CRYPTO_PB_H_MAX_SIZE com_daml_ledger_api_v2_Signature_size
#define com_daml_ledger_api_v2_Signature_size    2058
#define com_daml_ledger_api_v2_SigningPublicKey_size 1031

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
