/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com/daml/ledger/api/v2/event.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_daml_ledger_api_v2_Event, com_daml_ledger_api_v2_Event, 4)


PB_BIND(com_daml_ledger_api_v2_CreatedEvent, com_daml_ledger_api_v2_CreatedEvent, 4)


PB_BIND(com_daml_ledger_api_v2_InterfaceView, com_daml_ledger_api_v2_InterfaceView, 2)


PB_BIND(com_daml_ledger_api_v2_ArchivedEvent, com_daml_ledger_api_v2_ArchivedEvent, 2)


PB_BIND(com_daml_ledger_api_v2_ExercisedEvent, com_daml_ledger_api_v2_ExercisedEvent, 4)



