/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com/daml/ledger/api/v2/offset_checkpoint.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_daml_ledger_api_v2_OffsetCheckpoint, com_daml_ledger_api_v2_OffsetCheckpoint, AUTO)


PB_BIND(com_daml_ledger_api_v2_SynchronizerTime, com_daml_ledger_api_v2_SynchronizerTime, 2)



