# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/daml/ledger/api/v2/offset_checkpoint.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.com/daml/ledger/api/v2/offset_checkpoint.proto\x12\x16\x63om.daml.ledger.api.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"h\n\x10OffsetCheckpoint\x12\x0e\n\x06offset\x18\x01 \x01(\x03\x12\x44\n\x12synchronizer_times\x18\x02 \x03(\x0b\x32(.com.daml.ledger.api.v2.SynchronizerTime\"\\\n\x10SynchronizerTime\x12\x17\n\x0fsynchronizer_id\x18\x01 \x01(\t\x12/\n\x0brecord_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampBM\n\x16\x63om.daml.ledger.api.v2B\x1aOffsetCheckpointOuterClass\xaa\x02\x16\x43om.Daml.Ledger.Api.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.daml.ledger.api.v2.offset_checkpoint_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.daml.ledger.api.v2B\032OffsetCheckpointOuterClass\252\002\026Com.Daml.Ledger.Api.V2'
  _globals['_OFFSETCHECKPOINT']._serialized_start=107
  _globals['_OFFSETCHECKPOINT']._serialized_end=211
  _globals['_SYNCHRONIZERTIME']._serialized_start=213
  _globals['_SYNCHRONIZERTIME']._serialized_end=305
# @@protoc_insertion_point(module_scope)
