/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com/daml/ledger/api/v2/package_reference.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_daml_ledger_api_v2_PackageReference, com_daml_ledger_api_v2_PackageReference, 2)


PB_BIND(com_daml_ledger_api_v2_VettedPackage, com_daml_ledger_api_v2_VettedPackage, 2)


PB_BIND(com_daml_ledger_api_v2_VettedPackages, com_daml_ledger_api_v2_VettedPackages, 2)


PB_BIND(com_daml_ledger_api_v2_PriorTopologySerial, com_daml_ledger_api_v2_PriorTopologySerial, AUTO)



