/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_PACKAGE_REFERENCE_PB_H_INCLUDED
#define PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_PACKAGE_REFERENCE_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/empty.pb.h"
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _com_daml_ledger_api_v2_PackageReference {
    /* Required */
    char package_id[1024];
    /* Required */
    char package_name[1024];
    /* Required */
    char package_version[1024];
} com_daml_ledger_api_v2_PackageReference;

/* A package that is vetting on a given participant and synchronizer,
 modelled after ``VettedPackage`` in `topology.proto <https://github.com/digital-asset/canton/blob/main/community/base/src/main/protobuf/com/digitalasset/canton/protocol/v30/topology.proto#L206>`_,
 enriched with the package name and version. */
typedef struct _com_daml_ledger_api_v2_VettedPackage {
    /* Package ID of this package

 Required */
    char package_id[1024];
    /* The time from which this package is vetted. Empty if vetting time has no
 lower bound.

 Optional */
    bool has_valid_from_inclusive;
    google_protobuf_Timestamp valid_from_inclusive;
    /* The time until which this package is vetted. Empty if vetting time has no
 upper bound.

 Optional */
    bool has_valid_until_exclusive;
    google_protobuf_Timestamp valid_until_exclusive;
    /* Name of this package.
 Only available if the package has been uploaded to the current participant.

 Optional */
    char package_name[1024];
    /* Version of this package.
 Only available if the package has been uploaded to the current participant.

 Optional */
    char package_version[1024];
} com_daml_ledger_api_v2_VettedPackage;

/* The list of packages vetted on a given participant and synchronizer, modelled
 after ``VettedPackages`` in `topology.proto <https://github.com/digital-asset/canton/blob/main/community/base/src/main/protobuf/com/digitalasset/canton/protocol/v30/topology.proto#L206>`_.
 The list only contains packages that matched a filter in the query that
 originated it. */
typedef struct _com_daml_ledger_api_v2_VettedPackages {
    /* Sorted by package_name and package_version where known, and package_id as a
 last resort.

 Required: must be non-empty */
    pb_callback_t packages;
    /* Participant on which these packages are vetted.

 Required */
    char participant_id[1024];
    /* Synchronizer on which these packages are vetted.

 Required */
    char synchronizer_id[1024];
    /* Serial of last ``VettedPackages`` topology transaction of this participant
 and on this synchronizer.

 Required */
    uint32_t topology_serial;
} com_daml_ledger_api_v2_VettedPackages;

/* The serial of last ``VettedPackages`` topology transaction on a given
 participant and synchronizer. */
typedef struct _com_daml_ledger_api_v2_PriorTopologySerial {
    pb_size_t which_serial;
    union {
        /* Previous transaction's serial. */
        uint32_t prior;
        /* No previous transaction exists. */
        google_protobuf_Empty no_prior;
    } serial;
} com_daml_ledger_api_v2_PriorTopologySerial;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define com_daml_ledger_api_v2_PackageReference_init_default {"", "", ""}
#define com_daml_ledger_api_v2_VettedPackage_init_default {"", false, google_protobuf_Timestamp_init_default, false, google_protobuf_Timestamp_init_default, "", ""}
#define com_daml_ledger_api_v2_VettedPackages_init_default {{{NULL}, NULL}, "", "", 0}
#define com_daml_ledger_api_v2_PriorTopologySerial_init_default {0, {0}}
#define com_daml_ledger_api_v2_PackageReference_init_zero {"", "", ""}
#define com_daml_ledger_api_v2_VettedPackage_init_zero {"", false, google_protobuf_Timestamp_init_zero, false, google_protobuf_Timestamp_init_zero, "", ""}
#define com_daml_ledger_api_v2_VettedPackages_init_zero {{{NULL}, NULL}, "", "", 0}
#define com_daml_ledger_api_v2_PriorTopologySerial_init_zero {0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define com_daml_ledger_api_v2_PackageReference_package_id_tag 1
#define com_daml_ledger_api_v2_PackageReference_package_name_tag 2
#define com_daml_ledger_api_v2_PackageReference_package_version_tag 3
#define com_daml_ledger_api_v2_VettedPackage_package_id_tag 1
#define com_daml_ledger_api_v2_VettedPackage_valid_from_inclusive_tag 2
#define com_daml_ledger_api_v2_VettedPackage_valid_until_exclusive_tag 3
#define com_daml_ledger_api_v2_VettedPackage_package_name_tag 4
#define com_daml_ledger_api_v2_VettedPackage_package_version_tag 5
#define com_daml_ledger_api_v2_VettedPackages_packages_tag 1
#define com_daml_ledger_api_v2_VettedPackages_participant_id_tag 2
#define com_daml_ledger_api_v2_VettedPackages_synchronizer_id_tag 3
#define com_daml_ledger_api_v2_VettedPackages_topology_serial_tag 4
#define com_daml_ledger_api_v2_PriorTopologySerial_prior_tag 1
#define com_daml_ledger_api_v2_PriorTopologySerial_no_prior_tag 2

/* Struct field encoding specification for nanopb */
#define com_daml_ledger_api_v2_PackageReference_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   package_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   package_name,      2) \
X(a, STATIC,   SINGULAR, STRING,   package_version,   3)
#define com_daml_ledger_api_v2_PackageReference_CALLBACK NULL
#define com_daml_ledger_api_v2_PackageReference_DEFAULT NULL

#define com_daml_ledger_api_v2_VettedPackage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   package_id,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  valid_from_inclusive,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  valid_until_exclusive,   3) \
X(a, STATIC,   SINGULAR, STRING,   package_name,      4) \
X(a, STATIC,   SINGULAR, STRING,   package_version,   5)
#define com_daml_ledger_api_v2_VettedPackage_CALLBACK NULL
#define com_daml_ledger_api_v2_VettedPackage_DEFAULT NULL
#define com_daml_ledger_api_v2_VettedPackage_valid_from_inclusive_MSGTYPE google_protobuf_Timestamp
#define com_daml_ledger_api_v2_VettedPackage_valid_until_exclusive_MSGTYPE google_protobuf_Timestamp

#define com_daml_ledger_api_v2_VettedPackages_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  packages,          1) \
X(a, STATIC,   SINGULAR, STRING,   participant_id,    2) \
X(a, STATIC,   SINGULAR, STRING,   synchronizer_id,   3) \
X(a, STATIC,   SINGULAR, UINT32,   topology_serial,   4)
#define com_daml_ledger_api_v2_VettedPackages_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_VettedPackages_DEFAULT NULL
#define com_daml_ledger_api_v2_VettedPackages_packages_MSGTYPE com_daml_ledger_api_v2_VettedPackage

#define com_daml_ledger_api_v2_PriorTopologySerial_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (serial,prior,serial.prior),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (serial,no_prior,serial.no_prior),   2)
#define com_daml_ledger_api_v2_PriorTopologySerial_CALLBACK NULL
#define com_daml_ledger_api_v2_PriorTopologySerial_DEFAULT NULL
#define com_daml_ledger_api_v2_PriorTopologySerial_serial_no_prior_MSGTYPE google_protobuf_Empty

extern const pb_msgdesc_t com_daml_ledger_api_v2_PackageReference_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_VettedPackage_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_VettedPackages_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_PriorTopologySerial_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_daml_ledger_api_v2_PackageReference_fields &com_daml_ledger_api_v2_PackageReference_msg
#define com_daml_ledger_api_v2_VettedPackage_fields &com_daml_ledger_api_v2_VettedPackage_msg
#define com_daml_ledger_api_v2_VettedPackages_fields &com_daml_ledger_api_v2_VettedPackages_msg
#define com_daml_ledger_api_v2_PriorTopologySerial_fields &com_daml_ledger_api_v2_PriorTopologySerial_msg

/* Maximum encoded size of messages (where known) */
/* com_daml_ledger_api_v2_VettedPackages_size depends on runtime parameters */
#define COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_PACKAGE_REFERENCE_PB_H_MAX_SIZE com_daml_ledger_api_v2_VettedPackage_size
#define com_daml_ledger_api_v2_PackageReference_size 3078
#define com_daml_ledger_api_v2_PriorTopologySerial_size 6
#define com_daml_ledger_api_v2_VettedPackage_size 3126

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
