/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_TRACE_CONTEXT_PB_H_INCLUDED
#define PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_TRACE_CONTEXT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _com_daml_ledger_api_v2_TraceContext {
    /* https://www.w3.org/TR/trace-context/

 Optional */
    bool has_traceparent;
    char traceparent[1024];
    /* Optional */
    bool has_tracestate;
    char tracestate[1024];
} com_daml_ledger_api_v2_TraceContext;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define com_daml_ledger_api_v2_TraceContext_init_default {false, "", false, ""}
#define com_daml_ledger_api_v2_TraceContext_init_zero {false, "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define com_daml_ledger_api_v2_TraceContext_traceparent_tag 1
#define com_daml_ledger_api_v2_TraceContext_tracestate_tag 2

/* Struct field encoding specification for nanopb */
#define com_daml_ledger_api_v2_TraceContext_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   traceparent,       1) \
X(a, STATIC,   OPTIONAL, STRING,   tracestate,        2)
#define com_daml_ledger_api_v2_TraceContext_CALLBACK NULL
#define com_daml_ledger_api_v2_TraceContext_DEFAULT NULL

extern const pb_msgdesc_t com_daml_ledger_api_v2_TraceContext_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_daml_ledger_api_v2_TraceContext_fields &com_daml_ledger_api_v2_TraceContext_msg

/* Maximum encoded size of messages (where known) */
#define COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_TRACE_CONTEXT_PB_H_MAX_SIZE com_daml_ledger_api_v2_TraceContext_size
#define com_daml_ledger_api_v2_TraceContext_size 2052

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
