/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_TRANSACTION_PB_H_INCLUDED
#define PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_TRANSACTION_PB_H_INCLUDED
#include <pb.h>
#include "com/daml/ledger/api/v2/event.pb.h"
#include "com/daml/ledger/api/v2/trace_context.pb.h"
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1024) com_daml_ledger_api_v2_Transaction_external_transaction_hash_t;
/* Filtered view of an on-ledger transaction's create and archive events. */
typedef struct _com_daml_ledger_api_v2_Transaction {
    /* Assigned by the server. Useful for correlating logs.
 Must be a valid LedgerString (as described in ``value.proto``).
 Required */
    char update_id[1024];
    /* The ID of the command which resulted in this transaction. Missing for everyone except the submitting party.
 Must be a valid LedgerString (as described in ``value.proto``).
 Optional */
    char command_id[1024];
    /* The workflow ID used in command submission.
 Must be a valid LedgerString (as described in ``value.proto``).
 Optional */
    char workflow_id[1024];
    /* Ledger effective time.
 Required */
    bool has_effective_at;
    google_protobuf_Timestamp effective_at;
    /* The collection of events.
 Contains:

 - ``CreatedEvent`` or ``ArchivedEvent`` in case of ACS_DELTA transaction shape
 - ``CreatedEvent`` or ``ExercisedEvent`` in case of LEDGER_EFFECTS transaction shape

 Required */
    pb_callback_t events;
    /* The absolute offset. The details of this field are described in ``community/ledger-api/README.md``.
 Required, it is a valid absolute offset (positive integer). */
    int64_t offset;
    /* A valid synchronizer id.
 Identifies the synchronizer that synchronized the transaction.
 Required */
    char synchronizer_id[1024];
    /* Optional; ledger API trace context

 The trace context transported in this message corresponds to the trace context supplied
 by the client application in a HTTP2 header of the original command submission.
 We typically use a header to transfer this type of information. Here we use message
 body, because it is used in gRPC streams which do not support per message headers.
 This field will be populated with the trace context contained in the original submission.
 If that was not provided, a unique ledger-api-server generated trace context will be used
 instead. */
    bool has_trace_context;
    com_daml_ledger_api_v2_TraceContext trace_context;
    /* The time at which the transaction was recorded. The record time refers to the synchronizer
 which synchronized the transaction.
 Required */
    bool has_record_time;
    google_protobuf_Timestamp record_time;
    /* For transaction externally signed, contains the external transaction hash
 signed by the external party. Can be used to correlate an external submission with a committed transaction.
 Optional */
    bool has_external_transaction_hash;
    com_daml_ledger_api_v2_Transaction_external_transaction_hash_t external_transaction_hash;
} com_daml_ledger_api_v2_Transaction;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define com_daml_ledger_api_v2_Transaction_init_default {"", "", "", false, google_protobuf_Timestamp_init_default, {{NULL}, NULL}, 0, "", false, com_daml_ledger_api_v2_TraceContext_init_default, false, google_protobuf_Timestamp_init_default, false, {0, {0}}}
#define com_daml_ledger_api_v2_Transaction_init_zero {"", "", "", false, google_protobuf_Timestamp_init_zero, {{NULL}, NULL}, 0, "", false, com_daml_ledger_api_v2_TraceContext_init_zero, false, google_protobuf_Timestamp_init_zero, false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define com_daml_ledger_api_v2_Transaction_update_id_tag 1
#define com_daml_ledger_api_v2_Transaction_command_id_tag 2
#define com_daml_ledger_api_v2_Transaction_workflow_id_tag 3
#define com_daml_ledger_api_v2_Transaction_effective_at_tag 4
#define com_daml_ledger_api_v2_Transaction_events_tag 5
#define com_daml_ledger_api_v2_Transaction_offset_tag 6
#define com_daml_ledger_api_v2_Transaction_synchronizer_id_tag 7
#define com_daml_ledger_api_v2_Transaction_trace_context_tag 8
#define com_daml_ledger_api_v2_Transaction_record_time_tag 9
#define com_daml_ledger_api_v2_Transaction_external_transaction_hash_tag 10

/* Struct field encoding specification for nanopb */
#define com_daml_ledger_api_v2_Transaction_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   update_id,         1) \
X(a, STATIC,   SINGULAR, STRING,   command_id,        2) \
X(a, STATIC,   SINGULAR, STRING,   workflow_id,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  effective_at,      4) \
X(a, CALLBACK, REPEATED, MESSAGE,  events,            5) \
X(a, STATIC,   SINGULAR, INT64,    offset,            6) \
X(a, STATIC,   SINGULAR, STRING,   synchronizer_id,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  trace_context,     8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  record_time,       9) \
X(a, STATIC,   OPTIONAL, BYTES,    external_transaction_hash,  10)
#define com_daml_ledger_api_v2_Transaction_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_Transaction_DEFAULT NULL
#define com_daml_ledger_api_v2_Transaction_effective_at_MSGTYPE google_protobuf_Timestamp
#define com_daml_ledger_api_v2_Transaction_events_MSGTYPE com_daml_ledger_api_v2_Event
#define com_daml_ledger_api_v2_Transaction_trace_context_MSGTYPE com_daml_ledger_api_v2_TraceContext
#define com_daml_ledger_api_v2_Transaction_record_time_MSGTYPE google_protobuf_Timestamp

extern const pb_msgdesc_t com_daml_ledger_api_v2_Transaction_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_daml_ledger_api_v2_Transaction_fields &com_daml_ledger_api_v2_Transaction_msg

/* Maximum encoded size of messages (where known) */
/* com_daml_ledger_api_v2_Transaction_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
