/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com/daml/ledger/api/v2/transaction_filter.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_daml_ledger_api_v2_Filters, com_daml_ledger_api_v2_Filters, AUTO)


PB_BIND(com_daml_ledger_api_v2_CumulativeFilter, com_daml_ledger_api_v2_CumulativeFilter, 2)


PB_BIND(com_daml_ledger_api_v2_WildcardFilter, com_daml_ledger_api_v2_WildcardFilter, AUTO)


PB_BIND(com_daml_ledger_api_v2_InterfaceFilter, com_daml_ledger_api_v2_InterfaceFilter, 2)


PB_BIND(com_daml_ledger_api_v2_TemplateFilter, com_daml_ledger_api_v2_TemplateFilter, 2)


PB_BIND(com_daml_ledger_api_v2_EventFormat, com_daml_ledger_api_v2_EventFormat, AUTO)


PB_BIND(com_daml_ledger_api_v2_EventFormat_FiltersByPartyEntry, com_daml_ledger_api_v2_EventFormat_FiltersByPartyEntry, 2)


PB_BIND(com_daml_ledger_api_v2_TransactionFormat, com_daml_ledger_api_v2_TransactionFormat, AUTO)


PB_BIND(com_daml_ledger_api_v2_TopologyFormat, com_daml_ledger_api_v2_TopologyFormat, AUTO)


PB_BIND(com_daml_ledger_api_v2_ParticipantAuthorizationTopologyFormat, com_daml_ledger_api_v2_ParticipantAuthorizationTopologyFormat, AUTO)


PB_BIND(com_daml_ledger_api_v2_UpdateFormat, com_daml_ledger_api_v2_UpdateFormat, AUTO)





