/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com/daml/ledger/api/v2/value_cb.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_daml_ledger_api_v2_cb_Value, com_daml_ledger_api_v2_cb_Value, AUTO)


PB_BIND(com_daml_ledger_api_v2_cb_Record, com_daml_ledger_api_v2_cb_Record, AUTO)


PB_BIND(com_daml_ledger_api_v2_cb_RecordField, com_daml_ledger_api_v2_cb_RecordField, AUTO)


PB_BIND(com_daml_ledger_api_v2_cb_Identifier, com_daml_ledger_api_v2_cb_Identifier, AUTO)


PB_BIND(com_daml_ledger_api_v2_cb_Variant, com_daml_ledger_api_v2_cb_Variant, AUTO)


PB_BIND(com_daml_ledger_api_v2_cb_Enum, com_daml_ledger_api_v2_cb_Enum, AUTO)


PB_BIND(com_daml_ledger_api_v2_cb_List, com_daml_ledger_api_v2_cb_List, AUTO)


PB_BIND(com_daml_ledger_api_v2_cb_Optional, com_daml_ledger_api_v2_cb_Optional, AUTO)


PB_BIND(com_daml_ledger_api_v2_cb_TextMap, com_daml_ledger_api_v2_cb_TextMap, AUTO)


PB_BIND(com_daml_ledger_api_v2_cb_TextMap_Entry, com_daml_ledger_api_v2_cb_TextMap_Entry, AUTO)


PB_BIND(com_daml_ledger_api_v2_cb_GenMap, com_daml_ledger_api_v2_cb_GenMap, AUTO)


PB_BIND(com_daml_ledger_api_v2_cb_GenMap_Entry, com_daml_ledger_api_v2_cb_GenMap_Entry, AUTO)



