/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com/daml/ledger/api/v2/value.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_daml_ledger_api_v2_Value, com_daml_ledger_api_v2_Value, AUTO)


PB_BIND(com_daml_ledger_api_v2_Record, com_daml_ledger_api_v2_Record, AUTO)


PB_BIND(com_daml_ledger_api_v2_RecordField, com_daml_ledger_api_v2_RecordField, AUTO)


PB_BIND(com_daml_ledger_api_v2_Identifier, com_daml_ledger_api_v2_Identifier, AUTO)


PB_BIND(com_daml_ledger_api_v2_Variant, com_daml_ledger_api_v2_Variant, AUTO)


PB_BIND(com_daml_ledger_api_v2_Enum, com_daml_ledger_api_v2_Enum, AUTO)


PB_BIND(com_daml_ledger_api_v2_List, com_daml_ledger_api_v2_List, AUTO)


PB_BIND(com_daml_ledger_api_v2_Optional, com_daml_ledger_api_v2_Optional, AUTO)


PB_BIND(com_daml_ledger_api_v2_TextMap, com_daml_ledger_api_v2_TextMap, AUTO)


PB_BIND(com_daml_ledger_api_v2_TextMap_Entry, com_daml_ledger_api_v2_TextMap_Entry, AUTO)


PB_BIND(com_daml_ledger_api_v2_GenMap, com_daml_ledger_api_v2_GenMap, AUTO)


PB_BIND(com_daml_ledger_api_v2_GenMap_Entry, com_daml_ledger_api_v2_GenMap_Entry, AUTO)



