/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_VALUE_PB_H_INCLUDED
#define PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_VALUE_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/empty.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* A named nested value within a record. */
typedef struct _com_daml_ledger_api_v2_RecordField {
    /* When reading a transaction stream, it's omitted if verbose streaming is not enabled.
 When submitting a command, it's optional:

 - if all keys within a single record are present, the order in which fields appear does not matter. however, each key must appear exactly once.
 - if any of the keys within a single record are omitted, the order of fields MUST match the order of declaration in the Daml template.

 Must be a valid NameString */
    char *label;
    /* A nested value of a record.
 Required */
    struct _com_daml_ledger_api_v2_Value *value;
} com_daml_ledger_api_v2_RecordField;

/* Unique identifier of an entity.
 Throughout this API, the following terminology is being used:

   - if a Daml package-id is encoded in the package_id field, it is referred to as using a "package-id reference format"
   - if a Daml package-name is encoded in the package_id field, it is referred to as using a "package-name reference format" */
typedef struct _com_daml_ledger_api_v2_Identifier {
    /* Generally, the identifier of the Daml package that contains the entity.
 When encoding a package-id, it must be a valid PackageIdString.

 The field is overloaded to also be able to contain the package-name of the Daml package.
 This is supported if the entity referenced is either an interface or template.
 When representing the Daml package-name, the encoding is of form `#<package-name>`
 where `#` (not a valid package-id character)
 is used as a discriminator for signalling a package-name encoding.

 Required */
    char *package_id;
    /* The dot-separated module name of the identifier.
 Required */
    char *module_name;
    /* The dot-separated name of the entity (e.g. record, template, ...) within the module.
 Required */
    char *entity_name;
} com_daml_ledger_api_v2_Identifier;

/* Contains nested values. */
typedef struct _com_daml_ledger_api_v2_Record {
    /* Omitted from the transaction stream when verbose streaming is not enabled.
 Optional when submitting commands. */
    bool has_record_id;
    com_daml_ledger_api_v2_Identifier record_id;
    /* The nested values of the record.
 Required */
    pb_size_t fields_count;
    struct _com_daml_ledger_api_v2_RecordField *fields;
} com_daml_ledger_api_v2_Record;

/* A value with alternative representations. */
typedef struct _com_daml_ledger_api_v2_Variant {
    /* Omitted from the transaction stream when verbose streaming is not enabled.
 Optional when submitting commands. */
    bool has_variant_id;
    com_daml_ledger_api_v2_Identifier variant_id;
    /* Determines which of the Variant's alternatives is encoded in this message.
 Must be a valid NameString.
 Required */
    char *constructor;
    /* The value encoded within the Variant.
 Required */
    struct _com_daml_ledger_api_v2_Value *value;
} com_daml_ledger_api_v2_Variant;

/* A value with finite set of alternative representations. */
typedef struct _com_daml_ledger_api_v2_Enum {
    /* Omitted from the transaction stream when verbose streaming is not enabled.
 Optional when submitting commands. */
    bool has_enum_id;
    com_daml_ledger_api_v2_Identifier enum_id;
    /* Determines which of the Variant's alternatives is encoded in this message.
 Must be a valid NameString.
 Required */
    char *constructor;
} com_daml_ledger_api_v2_Enum;

/* A homogenous collection of values. */
typedef struct _com_daml_ledger_api_v2_List {
    /* The elements must all be of the same concrete value type.
 Optional */
    pb_size_t elements_count;
    struct _com_daml_ledger_api_v2_Value *elements;
} com_daml_ledger_api_v2_List;

/* Corresponds to Java's Optional type, Scala's Option, and Haskell's Maybe.
 The reason why we need to wrap this in an additional ``message`` is that we
 need to be able to encode the ``None`` case in the ``Value`` oneof. */
typedef struct _com_daml_ledger_api_v2_Optional {
    struct _com_daml_ledger_api_v2_Value *value; /* optional */
} com_daml_ledger_api_v2_Optional;

typedef struct _com_daml_ledger_api_v2_TextMap {
    pb_size_t entries_count;
    struct _com_daml_ledger_api_v2_TextMap_Entry *entries;
} com_daml_ledger_api_v2_TextMap;

typedef struct _com_daml_ledger_api_v2_TextMap_Entry {
    char *key;
    struct _com_daml_ledger_api_v2_Value *value;
} com_daml_ledger_api_v2_TextMap_Entry;

typedef struct _com_daml_ledger_api_v2_GenMap {
    pb_size_t entries_count;
    struct _com_daml_ledger_api_v2_GenMap_Entry *entries;
} com_daml_ledger_api_v2_GenMap;

/* Encodes values that the ledger accepts as command arguments and emits as contract arguments.

 The values encoding use different classes of non-empty strings as identifiers. Those classes are
 defined as follows:

 - NameStrings are strings with length <= 1000 that match the regexp ``[A-Za-z\$_][A-Za-z0-9\$_]*``.
 - PackageIdStrings are strings with length <= 64 that match the regexp ``[A-Za-z0-9\-_ ]+``.
 - PartyIdStrings are strings with length <= 255 that match the regexp ``[A-Za-z0-9:\-_ ]+``.
 - LedgerStrings are strings with length <= 255 that match the regexp ``[A-Za-z0-9#:\-_/ ]+``.
 - UserIdStrings are strings with length <= 128 that match the regexp ``[a-zA-Z0-9@^$.!`\-#+'~_|:]+``. */
typedef struct _com_daml_ledger_api_v2_Value {
    pb_size_t which_sum;
    union {
        /* This value is used for example for choices that don't take any arguments. */
        google_protobuf_Empty unit;
        /* True or false. */
        bool bool_;
        int64_t int64;
        /* Days since the unix epoch. Can go backwards. Limited from
     0001-01-01 to 9999-12-31, also to be compatible with
     https://www.ietf.org/rfc/rfc3339.txt */
        int32_t date;
        /* Microseconds since the UNIX epoch. Can go backwards. Fixed
     since the vast majority of values will be greater than
     2^28, since currently the number of microseconds since the
     epoch is greater than that. Range: 0001-01-01T00:00:00Z to
     9999-12-31T23:59:59.999999Z, so that we can convert to/from
     https://www.ietf.org/rfc/rfc3339.txt */
        int64_t timestamp;
        /* A Numeric, that is a decimal value with precision 38 (at most 38 significant digits) and a
     scale between 0 and 37 (significant digits on the right of the decimal point).
     The field has to match the regex
    
     .. code-block:: none
    
       [+-]?\d{1,38}(.\d{0,37})?
    
     and should be representable by a Numeric without loss of precision. */
        char *numeric;
        /* An agent operating on the ledger.
     Must be a valid PartyIdString. */
        char *party;
        /* A string. */
        char *text;
        /* Identifier of an on-ledger contract. Commands which reference an unknown or already archived contract ID will fail.
     Must be a valid LedgerString. */
        char *contract_id;
        /* The Optional type, None or Some */
        com_daml_ledger_api_v2_Optional optional;
        /* Represents a homogeneous list of values. */
        com_daml_ledger_api_v2_List list;
        /* The TextMap type */
        com_daml_ledger_api_v2_TextMap text_map;
        /* The GenMap type */
        com_daml_ledger_api_v2_GenMap gen_map;
        com_daml_ledger_api_v2_Record record;
        com_daml_ledger_api_v2_Variant variant;
        /* The Enum type */
        com_daml_ledger_api_v2_Enum enum_;
    };
} com_daml_ledger_api_v2_Value;

typedef struct _com_daml_ledger_api_v2_GenMap_Entry {
    struct _com_daml_ledger_api_v2_Value *key;
    struct _com_daml_ledger_api_v2_Value *value;
} com_daml_ledger_api_v2_GenMap_Entry;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define com_daml_ledger_api_v2_Value_init_default {0, {google_protobuf_Empty_init_default}}
#define com_daml_ledger_api_v2_Record_init_default {false, com_daml_ledger_api_v2_Identifier_init_default, 0, NULL}
#define com_daml_ledger_api_v2_RecordField_init_default {NULL, NULL}
#define com_daml_ledger_api_v2_Identifier_init_default {NULL, NULL, NULL}
#define com_daml_ledger_api_v2_Variant_init_default {false, com_daml_ledger_api_v2_Identifier_init_default, NULL, NULL}
#define com_daml_ledger_api_v2_Enum_init_default {false, com_daml_ledger_api_v2_Identifier_init_default, NULL}
#define com_daml_ledger_api_v2_List_init_default {0, NULL}
#define com_daml_ledger_api_v2_Optional_init_default {NULL}
#define com_daml_ledger_api_v2_TextMap_init_default {0, NULL}
#define com_daml_ledger_api_v2_TextMap_Entry_init_default {NULL, NULL}
#define com_daml_ledger_api_v2_GenMap_init_default {0, NULL}
#define com_daml_ledger_api_v2_GenMap_Entry_init_default {NULL, NULL}
#define com_daml_ledger_api_v2_Value_init_zero   {0, {google_protobuf_Empty_init_zero}}
#define com_daml_ledger_api_v2_Record_init_zero  {false, com_daml_ledger_api_v2_Identifier_init_zero, 0, NULL}
#define com_daml_ledger_api_v2_RecordField_init_zero {NULL, NULL}
#define com_daml_ledger_api_v2_Identifier_init_zero {NULL, NULL, NULL}
#define com_daml_ledger_api_v2_Variant_init_zero {false, com_daml_ledger_api_v2_Identifier_init_zero, NULL, NULL}
#define com_daml_ledger_api_v2_Enum_init_zero    {false, com_daml_ledger_api_v2_Identifier_init_zero, NULL}
#define com_daml_ledger_api_v2_List_init_zero    {0, NULL}
#define com_daml_ledger_api_v2_Optional_init_zero {NULL}
#define com_daml_ledger_api_v2_TextMap_init_zero {0, NULL}
#define com_daml_ledger_api_v2_TextMap_Entry_init_zero {NULL, NULL}
#define com_daml_ledger_api_v2_GenMap_init_zero  {0, NULL}
#define com_daml_ledger_api_v2_GenMap_Entry_init_zero {NULL, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define com_daml_ledger_api_v2_RecordField_label_tag 1
#define com_daml_ledger_api_v2_RecordField_value_tag 2
#define com_daml_ledger_api_v2_Identifier_package_id_tag 1
#define com_daml_ledger_api_v2_Identifier_module_name_tag 2
#define com_daml_ledger_api_v2_Identifier_entity_name_tag 3
#define com_daml_ledger_api_v2_Record_record_id_tag 1
#define com_daml_ledger_api_v2_Record_fields_tag 2
#define com_daml_ledger_api_v2_Variant_variant_id_tag 1
#define com_daml_ledger_api_v2_Variant_constructor_tag 2
#define com_daml_ledger_api_v2_Variant_value_tag 3
#define com_daml_ledger_api_v2_Enum_enum_id_tag  1
#define com_daml_ledger_api_v2_Enum_constructor_tag 2
#define com_daml_ledger_api_v2_List_elements_tag 1
#define com_daml_ledger_api_v2_Optional_value_tag 1
#define com_daml_ledger_api_v2_TextMap_entries_tag 1
#define com_daml_ledger_api_v2_TextMap_Entry_key_tag 1
#define com_daml_ledger_api_v2_TextMap_Entry_value_tag 2
#define com_daml_ledger_api_v2_GenMap_entries_tag 1
#define com_daml_ledger_api_v2_Value_unit_tag    1
#define com_daml_ledger_api_v2_Value_bool__tag   2
#define com_daml_ledger_api_v2_Value_int64_tag   3
#define com_daml_ledger_api_v2_Value_date_tag    4
#define com_daml_ledger_api_v2_Value_timestamp_tag 5
#define com_daml_ledger_api_v2_Value_numeric_tag 6
#define com_daml_ledger_api_v2_Value_party_tag   7
#define com_daml_ledger_api_v2_Value_text_tag    8
#define com_daml_ledger_api_v2_Value_contract_id_tag 9
#define com_daml_ledger_api_v2_Value_optional_tag 10
#define com_daml_ledger_api_v2_Value_list_tag    11
#define com_daml_ledger_api_v2_Value_text_map_tag 12
#define com_daml_ledger_api_v2_Value_gen_map_tag 13
#define com_daml_ledger_api_v2_Value_record_tag  14
#define com_daml_ledger_api_v2_Value_variant_tag 15
#define com_daml_ledger_api_v2_Value_enum__tag   16
#define com_daml_ledger_api_v2_GenMap_Entry_key_tag 1
#define com_daml_ledger_api_v2_GenMap_Entry_value_tag 2

/* Struct field encoding specification for nanopb */
#define com_daml_ledger_api_v2_Value_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (sum,unit,unit),   1) \
X(a, STATIC,   ONEOF,    BOOL,     (sum,bool_,bool_),   2) \
X(a, STATIC,   ONEOF,    SINT64,   (sum,int64,int64),   3) \
X(a, STATIC,   ONEOF,    INT32,    (sum,date,date),   4) \
X(a, STATIC,   ONEOF,    SFIXED64, (sum,timestamp,timestamp),   5) \
X(a, POINTER,  ONEOF,    STRING,   (sum,numeric,numeric),   6) \
X(a, POINTER,  ONEOF,    STRING,   (sum,party,party),   7) \
X(a, POINTER,  ONEOF,    STRING,   (sum,text,text),   8) \
X(a, POINTER,  ONEOF,    STRING,   (sum,contract_id,contract_id),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (sum,optional,optional),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (sum,list,list),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (sum,text_map,text_map),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (sum,gen_map,gen_map),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (sum,record,record),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (sum,variant,variant),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (sum,enum_,enum_),  16)
#define com_daml_ledger_api_v2_Value_CALLBACK NULL
#define com_daml_ledger_api_v2_Value_DEFAULT NULL
#define com_daml_ledger_api_v2_Value_sum_unit_MSGTYPE google_protobuf_Empty
#define com_daml_ledger_api_v2_Value_sum_optional_MSGTYPE com_daml_ledger_api_v2_Optional
#define com_daml_ledger_api_v2_Value_sum_list_MSGTYPE com_daml_ledger_api_v2_List
#define com_daml_ledger_api_v2_Value_sum_text_map_MSGTYPE com_daml_ledger_api_v2_TextMap
#define com_daml_ledger_api_v2_Value_sum_gen_map_MSGTYPE com_daml_ledger_api_v2_GenMap
#define com_daml_ledger_api_v2_Value_sum_record_MSGTYPE com_daml_ledger_api_v2_Record
#define com_daml_ledger_api_v2_Value_sum_variant_MSGTYPE com_daml_ledger_api_v2_Variant
#define com_daml_ledger_api_v2_Value_sum_enum__MSGTYPE com_daml_ledger_api_v2_Enum

#define com_daml_ledger_api_v2_Record_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  record_id,         1) \
X(a, POINTER,  REPEATED, MESSAGE,  fields,            2)
#define com_daml_ledger_api_v2_Record_CALLBACK NULL
#define com_daml_ledger_api_v2_Record_DEFAULT NULL
#define com_daml_ledger_api_v2_Record_record_id_MSGTYPE com_daml_ledger_api_v2_Identifier
#define com_daml_ledger_api_v2_Record_fields_MSGTYPE com_daml_ledger_api_v2_RecordField

#define com_daml_ledger_api_v2_RecordField_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   label,             1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  value,             2)
#define com_daml_ledger_api_v2_RecordField_CALLBACK NULL
#define com_daml_ledger_api_v2_RecordField_DEFAULT NULL
#define com_daml_ledger_api_v2_RecordField_value_MSGTYPE com_daml_ledger_api_v2_Value

#define com_daml_ledger_api_v2_Identifier_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   package_id,        1) \
X(a, POINTER,  SINGULAR, STRING,   module_name,       2) \
X(a, POINTER,  SINGULAR, STRING,   entity_name,       3)
#define com_daml_ledger_api_v2_Identifier_CALLBACK NULL
#define com_daml_ledger_api_v2_Identifier_DEFAULT NULL

#define com_daml_ledger_api_v2_Variant_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  variant_id,        1) \
X(a, POINTER,  SINGULAR, STRING,   constructor,       2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  value,             3)
#define com_daml_ledger_api_v2_Variant_CALLBACK NULL
#define com_daml_ledger_api_v2_Variant_DEFAULT NULL
#define com_daml_ledger_api_v2_Variant_variant_id_MSGTYPE com_daml_ledger_api_v2_Identifier
#define com_daml_ledger_api_v2_Variant_value_MSGTYPE com_daml_ledger_api_v2_Value

#define com_daml_ledger_api_v2_Enum_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  enum_id,           1) \
X(a, POINTER,  SINGULAR, STRING,   constructor,       2)
#define com_daml_ledger_api_v2_Enum_CALLBACK NULL
#define com_daml_ledger_api_v2_Enum_DEFAULT NULL
#define com_daml_ledger_api_v2_Enum_enum_id_MSGTYPE com_daml_ledger_api_v2_Identifier

#define com_daml_ledger_api_v2_List_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  elements,          1)
#define com_daml_ledger_api_v2_List_CALLBACK NULL
#define com_daml_ledger_api_v2_List_DEFAULT NULL
#define com_daml_ledger_api_v2_List_elements_MSGTYPE com_daml_ledger_api_v2_Value

#define com_daml_ledger_api_v2_Optional_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  value,             1)
#define com_daml_ledger_api_v2_Optional_CALLBACK NULL
#define com_daml_ledger_api_v2_Optional_DEFAULT NULL
#define com_daml_ledger_api_v2_Optional_value_MSGTYPE com_daml_ledger_api_v2_Value

#define com_daml_ledger_api_v2_TextMap_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  entries,           1)
#define com_daml_ledger_api_v2_TextMap_CALLBACK NULL
#define com_daml_ledger_api_v2_TextMap_DEFAULT NULL
#define com_daml_ledger_api_v2_TextMap_entries_MSGTYPE com_daml_ledger_api_v2_TextMap_Entry

#define com_daml_ledger_api_v2_TextMap_Entry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  value,             2)
#define com_daml_ledger_api_v2_TextMap_Entry_CALLBACK NULL
#define com_daml_ledger_api_v2_TextMap_Entry_DEFAULT NULL
#define com_daml_ledger_api_v2_TextMap_Entry_value_MSGTYPE com_daml_ledger_api_v2_Value

#define com_daml_ledger_api_v2_GenMap_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  entries,           1)
#define com_daml_ledger_api_v2_GenMap_CALLBACK NULL
#define com_daml_ledger_api_v2_GenMap_DEFAULT NULL
#define com_daml_ledger_api_v2_GenMap_entries_MSGTYPE com_daml_ledger_api_v2_GenMap_Entry

#define com_daml_ledger_api_v2_GenMap_Entry_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  key,               1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  value,             2)
#define com_daml_ledger_api_v2_GenMap_Entry_CALLBACK NULL
#define com_daml_ledger_api_v2_GenMap_Entry_DEFAULT NULL
#define com_daml_ledger_api_v2_GenMap_Entry_key_MSGTYPE com_daml_ledger_api_v2_Value
#define com_daml_ledger_api_v2_GenMap_Entry_value_MSGTYPE com_daml_ledger_api_v2_Value

extern const pb_msgdesc_t com_daml_ledger_api_v2_Value_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_Record_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_RecordField_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_Identifier_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_Variant_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_Enum_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_List_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_Optional_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_TextMap_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_TextMap_Entry_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_GenMap_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_GenMap_Entry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_daml_ledger_api_v2_Value_fields &com_daml_ledger_api_v2_Value_msg
#define com_daml_ledger_api_v2_Record_fields &com_daml_ledger_api_v2_Record_msg
#define com_daml_ledger_api_v2_RecordField_fields &com_daml_ledger_api_v2_RecordField_msg
#define com_daml_ledger_api_v2_Identifier_fields &com_daml_ledger_api_v2_Identifier_msg
#define com_daml_ledger_api_v2_Variant_fields &com_daml_ledger_api_v2_Variant_msg
#define com_daml_ledger_api_v2_Enum_fields &com_daml_ledger_api_v2_Enum_msg
#define com_daml_ledger_api_v2_List_fields &com_daml_ledger_api_v2_List_msg
#define com_daml_ledger_api_v2_Optional_fields &com_daml_ledger_api_v2_Optional_msg
#define com_daml_ledger_api_v2_TextMap_fields &com_daml_ledger_api_v2_TextMap_msg
#define com_daml_ledger_api_v2_TextMap_Entry_fields &com_daml_ledger_api_v2_TextMap_Entry_msg
#define com_daml_ledger_api_v2_GenMap_fields &com_daml_ledger_api_v2_GenMap_msg
#define com_daml_ledger_api_v2_GenMap_Entry_fields &com_daml_ledger_api_v2_GenMap_Entry_msg

/* Maximum encoded size of messages (where known) */
/* com_daml_ledger_api_v2_Value_size depends on runtime parameters */
/* com_daml_ledger_api_v2_Record_size depends on runtime parameters */
/* com_daml_ledger_api_v2_RecordField_size depends on runtime parameters */
/* com_daml_ledger_api_v2_Identifier_size depends on runtime parameters */
/* com_daml_ledger_api_v2_Variant_size depends on runtime parameters */
/* com_daml_ledger_api_v2_Enum_size depends on runtime parameters */
/* com_daml_ledger_api_v2_List_size depends on runtime parameters */
/* com_daml_ledger_api_v2_Optional_size depends on runtime parameters */
/* com_daml_ledger_api_v2_TextMap_size depends on runtime parameters */
/* com_daml_ledger_api_v2_TextMap_Entry_size depends on runtime parameters */
/* com_daml_ledger_api_v2_GenMap_size depends on runtime parameters */
/* com_daml_ledger_api_v2_GenMap_Entry_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
