/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GOOGLE_PROTOBUF_GOOGLE_PROTOBUF_ANY_PB_H_INCLUDED
#define PB_GOOGLE_PROTOBUF_GOOGLE_PROTOBUF_ANY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1024) google_protobuf_Any_value_t;
/* `Any` contains an arbitrary serialized protocol buffer message along with a
 URL that describes the type of the serialized message.

 In its binary encoding, an `Any` is an ordinary message; but in other wire
 forms like JSON, it has a special encoding. The format of the type URL is
 described on the `type_url` field.

 Protobuf APIs provide utilities to interact with `Any` values:

 - A 'pack' operation accepts a message and constructs a generic `Any` wrapper
   around it.
 - An 'unpack' operation reads the content of an `Any` message, either into an
   existing message or a new one. Unpack operations must check the type of the
   value they unpack against the declared `type_url`.
 - An 'is' operation decides whether an `Any` contains a message of the given
   type, i.e. whether it can 'unpack' that type.

 The JSON format representation of an `Any` follows one of these cases:

 - For types without special-cased JSON encodings, the JSON format
   representation of the `Any` is the same as that of the message, with an
   additional `@type` field which contains the type URL.
 - For types with special-cased JSON encodings (typically called 'well-known'
   types, listed in https://protobuf.dev/programming-guides/json/#any), the
   JSON format representation has a key `@type` which contains the type URL
   and a key `value` which contains the JSON-serialized value.

 The text format representation of an `Any` is like a message with one field
 whose name is the type URL in brackets. For example, an `Any` containing a
 `foo.Bar` message may be written `[type.googleapis.com/foo.Bar] { a: 2 }`. */
typedef struct _google_protobuf_Any {
    /* Identifies the type of the serialized Protobuf message with a URI reference
 consisting of a prefix ending in a slash and the fully-qualified type name.

 Example: type.googleapis.com/google.protobuf.StringValue

 This string must contain at least one `/` character, and the content after
 the last `/` must be the fully-qualified name of the type in canonical
 form, without a leading dot. Do not write a scheme on these URI references
 so that clients do not attempt to contact them.

 The prefix is arbitrary and Protobuf implementations are expected to
 simply strip off everything up to and including the last `/` to identify
 the type. `type.googleapis.com/` is a common default prefix that some
 legacy implementations require. This prefix does not indicate the origin of
 the type, and URIs containing it are not expected to respond to any
 requests.

 All type URL strings must be legal URI references with the additional
 restriction (for the text format) that the content of the reference
 must consist only of alphanumeric characters, percent-encoded escapes, and
 characters in the following set (not including the outer backticks):
 `/-.~_!$&()*+,;=`. Despite our allowing percent encodings, implementations
 should not unescape them to prevent confusion with existing parsers. For
 example, `type.googleapis.com%2FFoo` should be rejected.

 In the original design of `Any`, the possibility of launching a type
 resolution service at these type URLs was considered but Protobuf never
 implemented one and considers contacting these URLs to be problematic and
 a potential security issue. Do not attempt to contact type URLs. */
    char type_url[1024];
    /* Holds a Protobuf serialization of the type described by type_url. */
    google_protobuf_Any_value_t value;
} google_protobuf_Any;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define google_protobuf_Any_init_default         {"", {0, {0}}}
#define google_protobuf_Any_init_zero            {"", {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define google_protobuf_Any_type_url_tag         1
#define google_protobuf_Any_value_tag            2

/* Struct field encoding specification for nanopb */
#define google_protobuf_Any_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   type_url,          1) \
X(a, STATIC,   SINGULAR, BYTES,    value,             2)
#define google_protobuf_Any_CALLBACK NULL
#define google_protobuf_Any_DEFAULT NULL

extern const pb_msgdesc_t google_protobuf_Any_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_protobuf_Any_fields &google_protobuf_Any_msg

/* Maximum encoded size of messages (where known) */
#define GOOGLE_PROTOBUF_GOOGLE_PROTOBUF_ANY_PB_H_MAX_SIZE google_protobuf_Any_size
#define google_protobuf_Any_size                 2053

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
