/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com/daml/ledger/api/v2/interactive/transaction/v1/interactive_submission_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_daml_ledger_api_v2_interactive_transaction_v1_Fetch, com_daml_ledger_api_v2_interactive_transaction_v1_Fetch, 4)


PB_BIND(com_daml_ledger_api_v2_interactive_transaction_v1_Exercise, com_daml_ledger_api_v2_interactive_transaction_v1_Exercise, 4)


PB_BIND(com_daml_ledger_api_v2_interactive_transaction_v1_Create, com_daml_ledger_api_v2_interactive_transaction_v1_Create, 4)


PB_BIND(com_daml_ledger_api_v2_interactive_transaction_v1_Rollback, com_daml_ledger_api_v2_interactive_transaction_v1_Rollback, AUTO)


PB_BIND(com_daml_ledger_api_v2_interactive_transaction_v1_QueryByKey, com_daml_ledger_api_v2_interactive_transaction_v1_QueryByKey, 4)


PB_BIND(com_daml_ledger_api_v2_interactive_transaction_v1_Node, com_daml_ledger_api_v2_interactive_transaction_v1_Node, 4)



