/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_DIGITALASSET_CANTON_CRYPTO_V30_COM_DIGITALASSET_CANTON_CRYPTO_V30_CRYPTO_PB_H_INCLUDED
#define PB_COM_DIGITALASSET_CANTON_CRYPTO_V30_COM_DIGITALASSET_CANTON_CRYPTO_V30_CRYPTO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _com_digitalasset_canton_crypto_v30_HashAlgorithm {
    com_digitalasset_canton_crypto_v30_HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED = 0,
    com_digitalasset_canton_crypto_v30_HashAlgorithm_HASH_ALGORITHM_SHA256 = 1
} com_digitalasset_canton_crypto_v30_HashAlgorithm;

typedef enum _com_digitalasset_canton_crypto_v30_HmacAlgorithm {
    com_digitalasset_canton_crypto_v30_HmacAlgorithm_HMAC_ALGORITHM_UNSPECIFIED = 0,
    com_digitalasset_canton_crypto_v30_HmacAlgorithm_HMAC_ALGORITHM_HMAC_SHA256 = 1
} com_digitalasset_canton_crypto_v30_HmacAlgorithm;

typedef enum _com_digitalasset_canton_crypto_v30_SignatureFormat {
    com_digitalasset_canton_crypto_v30_SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED = 0,
    /* Signature scheme specific signature format
 Legacy format no longer used, except for migrations */
    com_digitalasset_canton_crypto_v30_SignatureFormat_SIGNATURE_FORMAT_RAW = 1,
    /* ASN.1 + DER-encoding of the `r` and `s` integers, as defined in https://datatracker.ietf.org/doc/html/rfc3279#section-2.2.3
 Used for ECDSA signatures */
    com_digitalasset_canton_crypto_v30_SignatureFormat_SIGNATURE_FORMAT_DER = 2,
    /* Concatenation of the integers `r || s` in little-endian form, as defined in https://datatracker.ietf.org/doc/html/rfc8032#section-3.3
 Note that this is different from the format defined in IEEE P1363, which uses concatenation in big-endian form.
 Used for EdDSA signatures */
    com_digitalasset_canton_crypto_v30_SignatureFormat_SIGNATURE_FORMAT_CONCAT = 3,
    /* Symbolic crypto, must only be used for testing */
    com_digitalasset_canton_crypto_v30_SignatureFormat_SIGNATURE_FORMAT_SYMBOLIC = 10000
} com_digitalasset_canton_crypto_v30_SignatureFormat;

typedef enum _com_digitalasset_canton_crypto_v30_EncryptionKeySpec {
    com_digitalasset_canton_crypto_v30_EncryptionKeySpec_ENCRYPTION_KEY_SPEC_UNSPECIFIED = 0,
    /* Elliptic Curve Key from the NIST P-256 curve (aka Secp256r1)
 as defined in https://doi.org/10.6028/NIST.FIPS.186-4 */
    com_digitalasset_canton_crypto_v30_EncryptionKeySpec_ENCRYPTION_KEY_SPEC_EC_P256 = 1,
    /* RSA with 2048 bits */
    com_digitalasset_canton_crypto_v30_EncryptionKeySpec_ENCRYPTION_KEY_SPEC_RSA_2048 = 2
} com_digitalasset_canton_crypto_v30_EncryptionKeySpec;

/* [start-docs-entry: signing key spec proto] */
typedef enum _com_digitalasset_canton_crypto_v30_SigningKeySpec {
    com_digitalasset_canton_crypto_v30_SigningKeySpec_SIGNING_KEY_SPEC_UNSPECIFIED = 0,
    /* Elliptic Curve Key from Curve25519
 as defined in http://ed25519.cr.yp.to/ */
    com_digitalasset_canton_crypto_v30_SigningKeySpec_SIGNING_KEY_SPEC_EC_CURVE25519 = 1,
    /* Elliptic Curve Key from the NIST P-256 curve (aka secp256r1)
 as defined in https://doi.org/10.6028/NIST.FIPS.186-4 */
    com_digitalasset_canton_crypto_v30_SigningKeySpec_SIGNING_KEY_SPEC_EC_P256 = 2,
    /* Elliptic Curve Key from the NIST P-384 curve (aka secp384r1)
 as defined in https://doi.org/10.6028/NIST.FIPS.186-4 */
    com_digitalasset_canton_crypto_v30_SigningKeySpec_SIGNING_KEY_SPEC_EC_P384 = 3,
    /* Elliptic Curve Key from SECG P256k1 curve (aka secp256k1)
 commonly used in bitcoin and ethereum
 as defined in https://www.secg.org/sec2-v2.pdf */
    com_digitalasset_canton_crypto_v30_SigningKeySpec_SIGNING_KEY_SPEC_EC_SECP256K1 = 4
} com_digitalasset_canton_crypto_v30_SigningKeySpec;

typedef enum _com_digitalasset_canton_crypto_v30_KeyPurpose {
    com_digitalasset_canton_crypto_v30_KeyPurpose_KEY_PURPOSE_UNSPECIFIED = 0,
    com_digitalasset_canton_crypto_v30_KeyPurpose_KEY_PURPOSE_SIGNING = 1,
    com_digitalasset_canton_crypto_v30_KeyPurpose_KEY_PURPOSE_ENCRYPTION = 2
} com_digitalasset_canton_crypto_v30_KeyPurpose;

typedef enum _com_digitalasset_canton_crypto_v30_SigningKeyUsage {
    com_digitalasset_canton_crypto_v30_SigningKeyUsage_SIGNING_KEY_USAGE_UNSPECIFIED = 0,
    /* the root namespace key that defines a node's identity and signs topology requests */
    com_digitalasset_canton_crypto_v30_SigningKeyUsage_SIGNING_KEY_USAGE_NAMESPACE = 1,
    /* No longer used (only kept for backwards compatibility) */
    com_digitalasset_canton_crypto_v30_SigningKeyUsage_SIGNING_KEY_USAGE_IDENTITY_DELEGATION = 2,
    /* keys that authenticate members of the network towards a sequencer */
    com_digitalasset_canton_crypto_v30_SigningKeyUsage_SIGNING_KEY_USAGE_SEQUENCER_AUTHENTICATION = 3,
    /* keys that deal with all the signing that happens as part of the protocol */
    com_digitalasset_canton_crypto_v30_SigningKeyUsage_SIGNING_KEY_USAGE_PROTOCOL = 4,
    /* used internally to identify keys that can self-sign to prove ownership */
    com_digitalasset_canton_crypto_v30_SigningKeyUsage_SIGNING_KEY_USAGE_PROOF_OF_OWNERSHIP = 5
} com_digitalasset_canton_crypto_v30_SigningKeyUsage;

typedef enum _com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec {
    com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_UNSPECIFIED = 0,
    /* EdDSA Signature based on Curve25519 with SHA-512
 http://ed25519.cr.yp.to/ */
    com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_ED25519 = 1,
    /* Elliptic Curve Digital Signature Algorithm with SHA256 */
    com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_256 = 2,
    /* Elliptic Curve Digital Signature Algorithm with SHA384 */
    com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384 = 3
} com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec;

/* @deprecated */
typedef enum _com_digitalasset_canton_crypto_v30_SigningKeyScheme {
    com_digitalasset_canton_crypto_v30_SigningKeyScheme_SIGNING_KEY_SCHEME_UNSPECIFIED = 0,
    /* Signature based on Curve25519
 http://ed25519.cr.yp.to/ */
    com_digitalasset_canton_crypto_v30_SigningKeyScheme_SIGNING_KEY_SCHEME_ED25519 = 1,
    /* EC-DSA with NIST curve P-256 or P-384 */
    com_digitalasset_canton_crypto_v30_SigningKeyScheme_SIGNING_KEY_SCHEME_EC_DSA_P256 = 2,
    com_digitalasset_canton_crypto_v30_SigningKeyScheme_SIGNING_KEY_SCHEME_EC_DSA_P384 = 3
} com_digitalasset_canton_crypto_v30_SigningKeyScheme;

typedef enum _com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec {
    com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec_ENCRYPTION_ALGORITHM_SPEC_UNSPECIFIED = 0,
    /* ECIES with ECDH, AES128 CBC, and HKDF and authentication (MAC) with HMAC-SHA256. This requires a P-256 key
because we use SHA256 and we need to align the lengths of the curve and the hash function. */
    com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec_ENCRYPTION_ALGORITHM_SPEC_ECIES_HKDF_HMAC_SHA256_AES128CBC = 1,
    /* RSA with OAEP Padding,
using SHA-256 for both the hash and in the MGF1 mask generation function along with an empty label. */
    com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec_ENCRYPTION_ALGORITHM_SPEC_RSA_OAEP_SHA256 = 2
} com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec;

/* @deprecated */
typedef enum _com_digitalasset_canton_crypto_v30_EncryptionKeyScheme {
    com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_ENCRYPTION_KEY_SCHEME_UNSPECIFIED = 0,
    /* ECIES with ECDH over NIST P-256, AES128 GCM, and HKDF with HMAC-SHA256 */
    com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_ENCRYPTION_KEY_SCHEME_ECIES_P256_HKDF_HMAC_SHA256_AES128GCM = 1,
    /* ECIES with ECDH over NIST P-256, AES128 CBC, and HKDF and authentication with HMAC-SHA256 */
    com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_ENCRYPTION_KEY_SCHEME_ECIES_P256_HMAC_SHA256A_ES128CBC = 2,
    /* RSA with a 2048 bit key with OAEP Padding,
using SHA-256 for both the hash and in the MGF1 mask generation function along with an empty label. */
    com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_ENCRYPTION_KEY_SCHEME_RSA2048_OAEP_SHA256 = 3
} com_digitalasset_canton_crypto_v30_EncryptionKeyScheme;

typedef enum _com_digitalasset_canton_crypto_v30_SymmetricKeyScheme {
    com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_SYMMETRIC_KEY_SCHEME_UNSPECIFIED = 0,
    /* AES with 128bit keys in GCM */
    com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_SYMMETRIC_KEY_SCHEME_AES128GCM = 1
} com_digitalasset_canton_crypto_v30_SymmetricKeyScheme;

/* Serialization format for crypto keys and signatures */
typedef enum _com_digitalasset_canton_crypto_v30_CryptoKeyFormat {
    com_digitalasset_canton_crypto_v30_CryptoKeyFormat_CRYPTO_KEY_FORMAT_UNSPECIFIED = 0,
    /* ASN.1 + DER encoding
 Legacy format no longer used, except for migrations */
    com_digitalasset_canton_crypto_v30_CryptoKeyFormat_CRYPTO_KEY_FORMAT_DER = 2,
    /* Raw encoding of a key, used for symmetric keys */
    com_digitalasset_canton_crypto_v30_CryptoKeyFormat_CRYPTO_KEY_FORMAT_RAW = 3,
    /* ASN.1 + DER-encoding of X.509 SubjectPublicKeyInfo structure: https://datatracker.ietf.org/doc/html/rfc5280#section-4.1 */
    com_digitalasset_canton_crypto_v30_CryptoKeyFormat_CRYPTO_KEY_FORMAT_DER_X509_SUBJECT_PUBLIC_KEY_INFO = 4,
    /* ASN.1 + DER-encoding of PKCS #8 PrivateKeyInfo structure: https://datatracker.ietf.org/doc/html/rfc5208#section-5 */
    com_digitalasset_canton_crypto_v30_CryptoKeyFormat_CRYPTO_KEY_FORMAT_DER_PKCS8_PRIVATE_KEY_INFO = 5,
    /* Symbolic crypto, must only be used for testing */
    com_digitalasset_canton_crypto_v30_CryptoKeyFormat_CRYPTO_KEY_FORMAT_SYMBOLIC = 10000
} com_digitalasset_canton_crypto_v30_CryptoKeyFormat;

typedef enum _com_digitalasset_canton_crypto_v30_PbkdfScheme {
    com_digitalasset_canton_crypto_v30_PbkdfScheme_PBKDF_SCHEME_UNSPECIFIED = 0,
    /* Argon2id with m=12288 (12 MiB), t=3, p=1 */
    com_digitalasset_canton_crypto_v30_PbkdfScheme_PBKDF_SCHEME_ARGON2ID_MODE1 = 1
} com_digitalasset_canton_crypto_v30_PbkdfScheme;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_Hmac_hmac_t;
typedef struct _com_digitalasset_canton_crypto_v30_Hmac {
    com_digitalasset_canton_crypto_v30_HmacAlgorithm algorithm;
    com_digitalasset_canton_crypto_v30_Hmac_hmac_t hmac;
} com_digitalasset_canton_crypto_v30_Hmac;

typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_Salt_salt_t;
typedef struct _com_digitalasset_canton_crypto_v30_Salt {
    pb_size_t which_algorithm;
    union {
        com_digitalasset_canton_crypto_v30_HmacAlgorithm hmac;
    } algorithm;
    com_digitalasset_canton_crypto_v30_Salt_salt_t salt;
} com_digitalasset_canton_crypto_v30_Salt;

typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_SignatureDelegation_session_key_t;
typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_SignatureDelegation_signature_t;
typedef struct _com_digitalasset_canton_crypto_v30_SignatureDelegation {
    /* ASN.1 + DER-encoding of X.509 SubjectPublicKeyInfo structure of the session public key:
 https://datatracker.ietf.org/doc/html/rfc5280#section-4.1. This key was used to produce the actual signature. */
    com_digitalasset_canton_crypto_v30_SignatureDelegation_session_key_t session_key;
    /* The signing key spec for the session key. */
    com_digitalasset_canton_crypto_v30_SigningKeySpec session_key_spec;
    /* A timestamp in microseconds of UTC time since Unix epoch that indicates when the session key is
 considered valid. */
    int64_t validity_period_from_inclusive;
    /* Duration in seconds indicating how long the session key remains valid.
 The validity period starts from `validity_period_from_inclusive` above. */
    uint32_t validity_period_duration_seconds;
    /* The format of the signature */
    com_digitalasset_canton_crypto_v30_SignatureFormat format;
    /* The signature of the combined hash of the session key fingerprint, validity period, and synchronizer id, by the
 long-term key. This signature authorizes the session key to act on behalf of the long-term key. */
    com_digitalasset_canton_crypto_v30_SignatureDelegation_signature_t signature;
    /* The signing algorithm specification used to produce this signature */
    com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec signing_algorithm_spec;
} com_digitalasset_canton_crypto_v30_SignatureDelegation;

typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_Signature_signature_t;
typedef struct _com_digitalasset_canton_crypto_v30_Signature {
    com_digitalasset_canton_crypto_v30_SignatureFormat format;
    com_digitalasset_canton_crypto_v30_Signature_signature_t signature;
    /* The fingerprint/id of the keypair used to create this signature and needed to verify.
 If a signature delegation is defined, this fingerprint/id is not used to produce the signature, and, instead
 is used to sign the delegation. */
    char signed_by[1024];
    /* The signing algorithm specification used to produce this signature */
    com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec signing_algorithm_spec;
    /* An optional signature delegation where a long-term signing key authorizes a session signing key to sign on its
 behalf. */
    bool has_signature_delegation;
    com_digitalasset_canton_crypto_v30_SignatureDelegation signature_delegation;
} com_digitalasset_canton_crypto_v30_Signature;

typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_SigningPublicKey_public_key_t;
typedef struct _com_digitalasset_canton_crypto_v30_SigningPublicKey {
    com_digitalasset_canton_crypto_v30_CryptoKeyFormat format;
    /* Serialized public key in the format specified above */
    com_digitalasset_canton_crypto_v30_SigningPublicKey_public_key_t public_key;
    /* No longer used (only kept for backwards compatibility) stores both the crypto key scheme and algorithm. */
    com_digitalasset_canton_crypto_v30_SigningKeyScheme scheme;
    /* Explicitly state the key's intended use */
    pb_callback_t usage;
    /* The key specification that was used to generate the key pair */
    com_digitalasset_canton_crypto_v30_SigningKeySpec key_spec;
} com_digitalasset_canton_crypto_v30_SigningPublicKey;

typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_SigningPrivateKey_private_key_t;
typedef struct _com_digitalasset_canton_crypto_v30_SigningPrivateKey {
    char id[1024];
    com_digitalasset_canton_crypto_v30_CryptoKeyFormat format;
    /* Serialized private key in the format specified above */
    com_digitalasset_canton_crypto_v30_SigningPrivateKey_private_key_t private_key;
    /* No longer used (only kept for backwards compatibility) stores both the crypto key scheme and algorithm. */
    com_digitalasset_canton_crypto_v30_SigningKeyScheme scheme;
    /* Explicitly state the key's intended use */
    pb_callback_t usage;
    /* The key specification that was used to generate the key pair */
    com_digitalasset_canton_crypto_v30_SigningKeySpec key_spec;
} com_digitalasset_canton_crypto_v30_SigningPrivateKey;

typedef struct _com_digitalasset_canton_crypto_v30_SigningKeyPair {
    bool has_private_key;
    com_digitalasset_canton_crypto_v30_SigningPrivateKey private_key;
} com_digitalasset_canton_crypto_v30_SigningKeyPair;

/* Used to announce the required signing key and algorithm specifications in the static synchronizer parameters. */
typedef struct _com_digitalasset_canton_crypto_v30_RequiredSigningSpecs {
    pb_callback_t algorithms;
    pb_callback_t keys;
} com_digitalasset_canton_crypto_v30_RequiredSigningSpecs;

typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_EncryptionPublicKey_public_key_t;
typedef struct _com_digitalasset_canton_crypto_v30_EncryptionPublicKey {
    com_digitalasset_canton_crypto_v30_CryptoKeyFormat format;
    /* Serialized public key in the format specified above */
    com_digitalasset_canton_crypto_v30_EncryptionPublicKey_public_key_t public_key;
    /* No longer used (only kept for backwards compatibility) stores both the crypto key scheme and algorithm. */
    com_digitalasset_canton_crypto_v30_EncryptionKeyScheme scheme;
    /* The key specification that was used to generate the key pair */
    com_digitalasset_canton_crypto_v30_EncryptionKeySpec key_spec;
} com_digitalasset_canton_crypto_v30_EncryptionPublicKey;

typedef struct _com_digitalasset_canton_crypto_v30_PublicKey {
    pb_size_t which_key;
    union {
        com_digitalasset_canton_crypto_v30_SigningPublicKey signing_public_key;
        com_digitalasset_canton_crypto_v30_EncryptionPublicKey encryption_public_key;
    } key;
} com_digitalasset_canton_crypto_v30_PublicKey;

typedef struct _com_digitalasset_canton_crypto_v30_PublicKeyWithName {
    bool has_public_key;
    com_digitalasset_canton_crypto_v30_PublicKey public_key;
    /* Optional name of the public key */
    char name[1024];
} com_digitalasset_canton_crypto_v30_PublicKeyWithName;

typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_private_key_t;
typedef struct _com_digitalasset_canton_crypto_v30_EncryptionPrivateKey {
    char id[1024];
    com_digitalasset_canton_crypto_v30_CryptoKeyFormat format;
    /* Serialized private key in the format specified above */
    com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_private_key_t private_key;
    /* No longer used (only kept for backwards compatibility) stores both the crypto key scheme and algorithm. */
    com_digitalasset_canton_crypto_v30_EncryptionKeyScheme scheme;
    /* The key specification that was used to generate the key pair */
    com_digitalasset_canton_crypto_v30_EncryptionKeySpec key_spec;
} com_digitalasset_canton_crypto_v30_EncryptionPrivateKey;

typedef struct _com_digitalasset_canton_crypto_v30_PrivateKey {
    pb_size_t which_key;
    union {
        com_digitalasset_canton_crypto_v30_SigningPrivateKey signing_private_key;
        com_digitalasset_canton_crypto_v30_EncryptionPrivateKey encryption_private_key;
    } key;
} com_digitalasset_canton_crypto_v30_PrivateKey;

typedef struct _com_digitalasset_canton_crypto_v30_EncryptionKeyPair {
    bool has_private_key;
    com_digitalasset_canton_crypto_v30_EncryptionPrivateKey private_key;
} com_digitalasset_canton_crypto_v30_EncryptionKeyPair;

/* Used to announce the required encryption key and algorithm specifications in the static synchronizer parameters. */
typedef struct _com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs {
    pb_callback_t algorithms;
    pb_callback_t keys;
} com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs;

typedef struct _com_digitalasset_canton_crypto_v30_CryptoKeyPair {
    pb_size_t which_pair;
    union {
        com_digitalasset_canton_crypto_v30_SigningKeyPair signing_key_pair;
        com_digitalasset_canton_crypto_v30_EncryptionKeyPair encryption_key_pair;
    } pair;
} com_digitalasset_canton_crypto_v30_CryptoKeyPair;

typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_SymmetricKey_key_t;
typedef struct _com_digitalasset_canton_crypto_v30_SymmetricKey {
    com_digitalasset_canton_crypto_v30_CryptoKeyFormat format;
    com_digitalasset_canton_crypto_v30_SymmetricKey_key_t key;
    com_digitalasset_canton_crypto_v30_SymmetricKeyScheme scheme;
} com_digitalasset_canton_crypto_v30_SymmetricKey;

typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_ciphertext_t;
typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_salt_t;
/* A password-based encrypted message */
typedef struct _com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted {
    com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_ciphertext_t ciphertext;
    /* The symmetric encryption scheme that was used to encrypt the plaintext */
    com_digitalasset_canton_crypto_v30_SymmetricKeyScheme symmetric_key_scheme;
    /* The password-based KDF that was used to derive the symmetric encryption key from the password */
    com_digitalasset_canton_crypto_v30_PbkdfScheme pbkdf_scheme;
    /* The random salt that was used to derive the symmetric encryption key from the password */
    com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_salt_t salt;
} com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted;

typedef PB_BYTES_ARRAY_T(1024) com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_ciphertext_t;
typedef struct _com_digitalasset_canton_crypto_v30_AsymmetricEncrypted {
    /* Asymmetrically encrypted data */
    com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_ciphertext_t ciphertext;
    /* The asymmetric encryption specification used for the encryption */
    com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec encryption_algorithm_spec;
    /* The fingerprint of the public key that was used for the encryption */
    char fingerprint[1024];
} com_digitalasset_canton_crypto_v30_AsymmetricEncrypted;

typedef struct _com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold {
    /* the designated signing keys */
    pb_callback_t keys;
    /* the authorization threshold */
    uint32_t threshold;
} com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _com_digitalasset_canton_crypto_v30_HashAlgorithm_MIN com_digitalasset_canton_crypto_v30_HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_HashAlgorithm_MAX com_digitalasset_canton_crypto_v30_HashAlgorithm_HASH_ALGORITHM_SHA256
#define _com_digitalasset_canton_crypto_v30_HashAlgorithm_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_HashAlgorithm)(com_digitalasset_canton_crypto_v30_HashAlgorithm_HASH_ALGORITHM_SHA256+1))

#define _com_digitalasset_canton_crypto_v30_HmacAlgorithm_MIN com_digitalasset_canton_crypto_v30_HmacAlgorithm_HMAC_ALGORITHM_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_HmacAlgorithm_MAX com_digitalasset_canton_crypto_v30_HmacAlgorithm_HMAC_ALGORITHM_HMAC_SHA256
#define _com_digitalasset_canton_crypto_v30_HmacAlgorithm_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_HmacAlgorithm)(com_digitalasset_canton_crypto_v30_HmacAlgorithm_HMAC_ALGORITHM_HMAC_SHA256+1))

#define _com_digitalasset_canton_crypto_v30_SignatureFormat_MIN com_digitalasset_canton_crypto_v30_SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_SignatureFormat_MAX com_digitalasset_canton_crypto_v30_SignatureFormat_SIGNATURE_FORMAT_SYMBOLIC
#define _com_digitalasset_canton_crypto_v30_SignatureFormat_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_SignatureFormat)(com_digitalasset_canton_crypto_v30_SignatureFormat_SIGNATURE_FORMAT_SYMBOLIC+1))

#define _com_digitalasset_canton_crypto_v30_EncryptionKeySpec_MIN com_digitalasset_canton_crypto_v30_EncryptionKeySpec_ENCRYPTION_KEY_SPEC_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_EncryptionKeySpec_MAX com_digitalasset_canton_crypto_v30_EncryptionKeySpec_ENCRYPTION_KEY_SPEC_RSA_2048
#define _com_digitalasset_canton_crypto_v30_EncryptionKeySpec_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_EncryptionKeySpec)(com_digitalasset_canton_crypto_v30_EncryptionKeySpec_ENCRYPTION_KEY_SPEC_RSA_2048+1))

#define _com_digitalasset_canton_crypto_v30_SigningKeySpec_MIN com_digitalasset_canton_crypto_v30_SigningKeySpec_SIGNING_KEY_SPEC_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_SigningKeySpec_MAX com_digitalasset_canton_crypto_v30_SigningKeySpec_SIGNING_KEY_SPEC_EC_SECP256K1
#define _com_digitalasset_canton_crypto_v30_SigningKeySpec_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_SigningKeySpec)(com_digitalasset_canton_crypto_v30_SigningKeySpec_SIGNING_KEY_SPEC_EC_SECP256K1+1))

#define _com_digitalasset_canton_crypto_v30_KeyPurpose_MIN com_digitalasset_canton_crypto_v30_KeyPurpose_KEY_PURPOSE_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_KeyPurpose_MAX com_digitalasset_canton_crypto_v30_KeyPurpose_KEY_PURPOSE_ENCRYPTION
#define _com_digitalasset_canton_crypto_v30_KeyPurpose_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_KeyPurpose)(com_digitalasset_canton_crypto_v30_KeyPurpose_KEY_PURPOSE_ENCRYPTION+1))

#define _com_digitalasset_canton_crypto_v30_SigningKeyUsage_MIN com_digitalasset_canton_crypto_v30_SigningKeyUsage_SIGNING_KEY_USAGE_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_SigningKeyUsage_MAX com_digitalasset_canton_crypto_v30_SigningKeyUsage_SIGNING_KEY_USAGE_PROOF_OF_OWNERSHIP
#define _com_digitalasset_canton_crypto_v30_SigningKeyUsage_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_SigningKeyUsage)(com_digitalasset_canton_crypto_v30_SigningKeyUsage_SIGNING_KEY_USAGE_PROOF_OF_OWNERSHIP+1))

#define _com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_MIN com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_MAX com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384
#define _com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec)(com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384+1))

#define _com_digitalasset_canton_crypto_v30_SigningKeyScheme_MIN com_digitalasset_canton_crypto_v30_SigningKeyScheme_SIGNING_KEY_SCHEME_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_SigningKeyScheme_MAX com_digitalasset_canton_crypto_v30_SigningKeyScheme_SIGNING_KEY_SCHEME_EC_DSA_P384
#define _com_digitalasset_canton_crypto_v30_SigningKeyScheme_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_SigningKeyScheme)(com_digitalasset_canton_crypto_v30_SigningKeyScheme_SIGNING_KEY_SCHEME_EC_DSA_P384+1))

#define _com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec_MIN com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec_ENCRYPTION_ALGORITHM_SPEC_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec_MAX com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec_ENCRYPTION_ALGORITHM_SPEC_RSA_OAEP_SHA256
#define _com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec)(com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec_ENCRYPTION_ALGORITHM_SPEC_RSA_OAEP_SHA256+1))

#define _com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_MIN com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_ENCRYPTION_KEY_SCHEME_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_MAX com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_ENCRYPTION_KEY_SCHEME_RSA2048_OAEP_SHA256
#define _com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_EncryptionKeyScheme)(com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_ENCRYPTION_KEY_SCHEME_RSA2048_OAEP_SHA256+1))

#define _com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_MIN com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_SYMMETRIC_KEY_SCHEME_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_MAX com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_SYMMETRIC_KEY_SCHEME_AES128GCM
#define _com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_SymmetricKeyScheme)(com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_SYMMETRIC_KEY_SCHEME_AES128GCM+1))

#define _com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MIN com_digitalasset_canton_crypto_v30_CryptoKeyFormat_CRYPTO_KEY_FORMAT_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MAX com_digitalasset_canton_crypto_v30_CryptoKeyFormat_CRYPTO_KEY_FORMAT_SYMBOLIC
#define _com_digitalasset_canton_crypto_v30_CryptoKeyFormat_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_CryptoKeyFormat)(com_digitalasset_canton_crypto_v30_CryptoKeyFormat_CRYPTO_KEY_FORMAT_SYMBOLIC+1))

#define _com_digitalasset_canton_crypto_v30_PbkdfScheme_MIN com_digitalasset_canton_crypto_v30_PbkdfScheme_PBKDF_SCHEME_UNSPECIFIED
#define _com_digitalasset_canton_crypto_v30_PbkdfScheme_MAX com_digitalasset_canton_crypto_v30_PbkdfScheme_PBKDF_SCHEME_ARGON2ID_MODE1
#define _com_digitalasset_canton_crypto_v30_PbkdfScheme_ARRAYSIZE ((com_digitalasset_canton_crypto_v30_PbkdfScheme)(com_digitalasset_canton_crypto_v30_PbkdfScheme_PBKDF_SCHEME_ARGON2ID_MODE1+1))

#define com_digitalasset_canton_crypto_v30_Hmac_algorithm_ENUMTYPE com_digitalasset_canton_crypto_v30_HmacAlgorithm

#define com_digitalasset_canton_crypto_v30_Salt_algorithm_hmac_ENUMTYPE com_digitalasset_canton_crypto_v30_HmacAlgorithm

#define com_digitalasset_canton_crypto_v30_Signature_format_ENUMTYPE com_digitalasset_canton_crypto_v30_SignatureFormat
#define com_digitalasset_canton_crypto_v30_Signature_signing_algorithm_spec_ENUMTYPE com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec

#define com_digitalasset_canton_crypto_v30_SignatureDelegation_session_key_spec_ENUMTYPE com_digitalasset_canton_crypto_v30_SigningKeySpec
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_format_ENUMTYPE com_digitalasset_canton_crypto_v30_SignatureFormat
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_signing_algorithm_spec_ENUMTYPE com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec




#define com_digitalasset_canton_crypto_v30_SigningPublicKey_format_ENUMTYPE com_digitalasset_canton_crypto_v30_CryptoKeyFormat
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_scheme_ENUMTYPE com_digitalasset_canton_crypto_v30_SigningKeyScheme
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_usage_ENUMTYPE com_digitalasset_canton_crypto_v30_SigningKeyUsage
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_key_spec_ENUMTYPE com_digitalasset_canton_crypto_v30_SigningKeySpec

#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_format_ENUMTYPE com_digitalasset_canton_crypto_v30_CryptoKeyFormat
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_scheme_ENUMTYPE com_digitalasset_canton_crypto_v30_SigningKeyScheme
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_usage_ENUMTYPE com_digitalasset_canton_crypto_v30_SigningKeyUsage
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_key_spec_ENUMTYPE com_digitalasset_canton_crypto_v30_SigningKeySpec


#define com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_algorithms_ENUMTYPE com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec
#define com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_keys_ENUMTYPE com_digitalasset_canton_crypto_v30_SigningKeySpec

#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_format_ENUMTYPE com_digitalasset_canton_crypto_v30_CryptoKeyFormat
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_scheme_ENUMTYPE com_digitalasset_canton_crypto_v30_EncryptionKeyScheme
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_key_spec_ENUMTYPE com_digitalasset_canton_crypto_v30_EncryptionKeySpec

#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_format_ENUMTYPE com_digitalasset_canton_crypto_v30_CryptoKeyFormat
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_scheme_ENUMTYPE com_digitalasset_canton_crypto_v30_EncryptionKeyScheme
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_key_spec_ENUMTYPE com_digitalasset_canton_crypto_v30_EncryptionKeySpec


#define com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_algorithms_ENUMTYPE com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec
#define com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_keys_ENUMTYPE com_digitalasset_canton_crypto_v30_EncryptionKeySpec


#define com_digitalasset_canton_crypto_v30_SymmetricKey_format_ENUMTYPE com_digitalasset_canton_crypto_v30_CryptoKeyFormat
#define com_digitalasset_canton_crypto_v30_SymmetricKey_scheme_ENUMTYPE com_digitalasset_canton_crypto_v30_SymmetricKeyScheme

#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_symmetric_key_scheme_ENUMTYPE com_digitalasset_canton_crypto_v30_SymmetricKeyScheme
#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_pbkdf_scheme_ENUMTYPE com_digitalasset_canton_crypto_v30_PbkdfScheme

#define com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_encryption_algorithm_spec_ENUMTYPE com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec



/* Initializer values for message structs */
#define com_digitalasset_canton_crypto_v30_Hmac_init_default {_com_digitalasset_canton_crypto_v30_HmacAlgorithm_MIN, {0, {0}}}
#define com_digitalasset_canton_crypto_v30_Salt_init_default {0, {_com_digitalasset_canton_crypto_v30_HmacAlgorithm_MIN}, {0, {0}}}
#define com_digitalasset_canton_crypto_v30_Signature_init_default {_com_digitalasset_canton_crypto_v30_SignatureFormat_MIN, {0, {0}}, "", _com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_MIN, false, com_digitalasset_canton_crypto_v30_SignatureDelegation_init_default}
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_init_default {{0, {0}}, _com_digitalasset_canton_crypto_v30_SigningKeySpec_MIN, 0, 0, _com_digitalasset_canton_crypto_v30_SignatureFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_MIN}
#define com_digitalasset_canton_crypto_v30_PublicKey_init_default {0, {com_digitalasset_canton_crypto_v30_SigningPublicKey_init_default}}
#define com_digitalasset_canton_crypto_v30_PublicKeyWithName_init_default {false, com_digitalasset_canton_crypto_v30_PublicKey_init_default, ""}
#define com_digitalasset_canton_crypto_v30_PrivateKey_init_default {0, {com_digitalasset_canton_crypto_v30_SigningPrivateKey_init_default}}
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_init_default {_com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_SigningKeyScheme_MIN, {{NULL}, NULL}, _com_digitalasset_canton_crypto_v30_SigningKeySpec_MIN}
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_init_default {"", _com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_SigningKeyScheme_MIN, {{NULL}, NULL}, _com_digitalasset_canton_crypto_v30_SigningKeySpec_MIN}
#define com_digitalasset_canton_crypto_v30_SigningKeyPair_init_default {false, com_digitalasset_canton_crypto_v30_SigningPrivateKey_init_default}
#define com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_init_default {_com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_MIN, _com_digitalasset_canton_crypto_v30_EncryptionKeySpec_MIN}
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_init_default {"", _com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_MIN, _com_digitalasset_canton_crypto_v30_EncryptionKeySpec_MIN}
#define com_digitalasset_canton_crypto_v30_EncryptionKeyPair_init_default {false, com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_init_default}
#define com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define com_digitalasset_canton_crypto_v30_CryptoKeyPair_init_default {0, {com_digitalasset_canton_crypto_v30_SigningKeyPair_init_default}}
#define com_digitalasset_canton_crypto_v30_SymmetricKey_init_default {_com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_MIN}
#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_init_default {{0, {0}}, _com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_MIN, _com_digitalasset_canton_crypto_v30_PbkdfScheme_MIN, {0, {0}}}
#define com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_init_default {{0, {0}}, _com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec_MIN, ""}
#define com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_init_default {{{NULL}, NULL}, 0}
#define com_digitalasset_canton_crypto_v30_Hmac_init_zero {_com_digitalasset_canton_crypto_v30_HmacAlgorithm_MIN, {0, {0}}}
#define com_digitalasset_canton_crypto_v30_Salt_init_zero {0, {_com_digitalasset_canton_crypto_v30_HmacAlgorithm_MIN}, {0, {0}}}
#define com_digitalasset_canton_crypto_v30_Signature_init_zero {_com_digitalasset_canton_crypto_v30_SignatureFormat_MIN, {0, {0}}, "", _com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_MIN, false, com_digitalasset_canton_crypto_v30_SignatureDelegation_init_zero}
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_init_zero {{0, {0}}, _com_digitalasset_canton_crypto_v30_SigningKeySpec_MIN, 0, 0, _com_digitalasset_canton_crypto_v30_SignatureFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_SigningAlgorithmSpec_MIN}
#define com_digitalasset_canton_crypto_v30_PublicKey_init_zero {0, {com_digitalasset_canton_crypto_v30_SigningPublicKey_init_zero}}
#define com_digitalasset_canton_crypto_v30_PublicKeyWithName_init_zero {false, com_digitalasset_canton_crypto_v30_PublicKey_init_zero, ""}
#define com_digitalasset_canton_crypto_v30_PrivateKey_init_zero {0, {com_digitalasset_canton_crypto_v30_SigningPrivateKey_init_zero}}
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_init_zero {_com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_SigningKeyScheme_MIN, {{NULL}, NULL}, _com_digitalasset_canton_crypto_v30_SigningKeySpec_MIN}
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_init_zero {"", _com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_SigningKeyScheme_MIN, {{NULL}, NULL}, _com_digitalasset_canton_crypto_v30_SigningKeySpec_MIN}
#define com_digitalasset_canton_crypto_v30_SigningKeyPair_init_zero {false, com_digitalasset_canton_crypto_v30_SigningPrivateKey_init_zero}
#define com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_init_zero {_com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_MIN, _com_digitalasset_canton_crypto_v30_EncryptionKeySpec_MIN}
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_init_zero {"", _com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_EncryptionKeyScheme_MIN, _com_digitalasset_canton_crypto_v30_EncryptionKeySpec_MIN}
#define com_digitalasset_canton_crypto_v30_EncryptionKeyPair_init_zero {false, com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_init_zero}
#define com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define com_digitalasset_canton_crypto_v30_CryptoKeyPair_init_zero {0, {com_digitalasset_canton_crypto_v30_SigningKeyPair_init_zero}}
#define com_digitalasset_canton_crypto_v30_SymmetricKey_init_zero {_com_digitalasset_canton_crypto_v30_CryptoKeyFormat_MIN, {0, {0}}, _com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_MIN}
#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_init_zero {{0, {0}}, _com_digitalasset_canton_crypto_v30_SymmetricKeyScheme_MIN, _com_digitalasset_canton_crypto_v30_PbkdfScheme_MIN, {0, {0}}}
#define com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_init_zero {{0, {0}}, _com_digitalasset_canton_crypto_v30_EncryptionAlgorithmSpec_MIN, ""}
#define com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_init_zero {{{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define com_digitalasset_canton_crypto_v30_Hmac_algorithm_tag 1
#define com_digitalasset_canton_crypto_v30_Hmac_hmac_tag 2
#define com_digitalasset_canton_crypto_v30_Salt_hmac_tag 1
#define com_digitalasset_canton_crypto_v30_Salt_salt_tag 2
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_session_key_tag 1
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_session_key_spec_tag 2
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_validity_period_from_inclusive_tag 3
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_validity_period_duration_seconds_tag 4
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_format_tag 5
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_signature_tag 6
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_signing_algorithm_spec_tag 7
#define com_digitalasset_canton_crypto_v30_Signature_format_tag 1
#define com_digitalasset_canton_crypto_v30_Signature_signature_tag 2
#define com_digitalasset_canton_crypto_v30_Signature_signed_by_tag 3
#define com_digitalasset_canton_crypto_v30_Signature_signing_algorithm_spec_tag 4
#define com_digitalasset_canton_crypto_v30_Signature_signature_delegation_tag 5
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_format_tag 2
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_public_key_tag 3
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_scheme_tag 4
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_usage_tag 5
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_key_spec_tag 6
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_id_tag 1
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_format_tag 2
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_private_key_tag 3
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_scheme_tag 4
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_usage_tag 5
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_key_spec_tag 6
#define com_digitalasset_canton_crypto_v30_SigningKeyPair_private_key_tag 2
#define com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_algorithms_tag 1
#define com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_keys_tag 2
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_format_tag 2
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_public_key_tag 3
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_scheme_tag 4
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_key_spec_tag 5
#define com_digitalasset_canton_crypto_v30_PublicKey_signing_public_key_tag 1
#define com_digitalasset_canton_crypto_v30_PublicKey_encryption_public_key_tag 2
#define com_digitalasset_canton_crypto_v30_PublicKeyWithName_public_key_tag 1
#define com_digitalasset_canton_crypto_v30_PublicKeyWithName_name_tag 2
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_id_tag 1
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_format_tag 2
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_private_key_tag 3
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_scheme_tag 4
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_key_spec_tag 5
#define com_digitalasset_canton_crypto_v30_PrivateKey_signing_private_key_tag 1
#define com_digitalasset_canton_crypto_v30_PrivateKey_encryption_private_key_tag 2
#define com_digitalasset_canton_crypto_v30_EncryptionKeyPair_private_key_tag 2
#define com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_algorithms_tag 1
#define com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_keys_tag 2
#define com_digitalasset_canton_crypto_v30_CryptoKeyPair_signing_key_pair_tag 1
#define com_digitalasset_canton_crypto_v30_CryptoKeyPair_encryption_key_pair_tag 2
#define com_digitalasset_canton_crypto_v30_SymmetricKey_format_tag 1
#define com_digitalasset_canton_crypto_v30_SymmetricKey_key_tag 2
#define com_digitalasset_canton_crypto_v30_SymmetricKey_scheme_tag 3
#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_ciphertext_tag 1
#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_symmetric_key_scheme_tag 2
#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_pbkdf_scheme_tag 3
#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_salt_tag 4
#define com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_ciphertext_tag 1
#define com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_encryption_algorithm_spec_tag 2
#define com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_fingerprint_tag 3
#define com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_keys_tag 1
#define com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_threshold_tag 2

/* Struct field encoding specification for nanopb */
#define com_digitalasset_canton_crypto_v30_Hmac_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    algorithm,         1) \
X(a, STATIC,   SINGULAR, BYTES,    hmac,              2)
#define com_digitalasset_canton_crypto_v30_Hmac_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_Hmac_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_Salt_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (algorithm,hmac,algorithm.hmac),   1) \
X(a, STATIC,   SINGULAR, BYTES,    salt,              2)
#define com_digitalasset_canton_crypto_v30_Salt_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_Salt_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_Signature_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    format,            1) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         2) \
X(a, STATIC,   SINGULAR, STRING,   signed_by,         3) \
X(a, STATIC,   SINGULAR, UENUM,    signing_algorithm_spec,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  signature_delegation,   5)
#define com_digitalasset_canton_crypto_v30_Signature_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_Signature_DEFAULT NULL
#define com_digitalasset_canton_crypto_v30_Signature_signature_delegation_MSGTYPE com_digitalasset_canton_crypto_v30_SignatureDelegation

#define com_digitalasset_canton_crypto_v30_SignatureDelegation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    session_key,       1) \
X(a, STATIC,   SINGULAR, UENUM,    session_key_spec,   2) \
X(a, STATIC,   SINGULAR, INT64,    validity_period_from_inclusive,   3) \
X(a, STATIC,   SINGULAR, UINT32,   validity_period_duration_seconds,   4) \
X(a, STATIC,   SINGULAR, UENUM,    format,            5) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         6) \
X(a, STATIC,   SINGULAR, UENUM,    signing_algorithm_spec,   7)
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_PublicKey_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (key,signing_public_key,key.signing_public_key),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (key,encryption_public_key,key.encryption_public_key),   2)
#define com_digitalasset_canton_crypto_v30_PublicKey_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_PublicKey_DEFAULT NULL
#define com_digitalasset_canton_crypto_v30_PublicKey_key_signing_public_key_MSGTYPE com_digitalasset_canton_crypto_v30_SigningPublicKey
#define com_digitalasset_canton_crypto_v30_PublicKey_key_encryption_public_key_MSGTYPE com_digitalasset_canton_crypto_v30_EncryptionPublicKey

#define com_digitalasset_canton_crypto_v30_PublicKeyWithName_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  public_key,        1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2)
#define com_digitalasset_canton_crypto_v30_PublicKeyWithName_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_PublicKeyWithName_DEFAULT NULL
#define com_digitalasset_canton_crypto_v30_PublicKeyWithName_public_key_MSGTYPE com_digitalasset_canton_crypto_v30_PublicKey

#define com_digitalasset_canton_crypto_v30_PrivateKey_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (key,signing_private_key,key.signing_private_key),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (key,encryption_private_key,key.encryption_private_key),   2)
#define com_digitalasset_canton_crypto_v30_PrivateKey_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_PrivateKey_DEFAULT NULL
#define com_digitalasset_canton_crypto_v30_PrivateKey_key_signing_private_key_MSGTYPE com_digitalasset_canton_crypto_v30_SigningPrivateKey
#define com_digitalasset_canton_crypto_v30_PrivateKey_key_encryption_private_key_MSGTYPE com_digitalasset_canton_crypto_v30_EncryptionPrivateKey

#define com_digitalasset_canton_crypto_v30_SigningPublicKey_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    format,            2) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,        3) \
X(a, STATIC,   SINGULAR, UENUM,    scheme,            4) \
X(a, CALLBACK, REPEATED, UENUM,    usage,             5) \
X(a, STATIC,   SINGULAR, UENUM,    key_spec,          6)
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_CALLBACK pb_default_field_callback
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    format,            2) \
X(a, STATIC,   SINGULAR, BYTES,    private_key,       3) \
X(a, STATIC,   SINGULAR, UENUM,    scheme,            4) \
X(a, CALLBACK, REPEATED, UENUM,    usage,             5) \
X(a, STATIC,   SINGULAR, UENUM,    key_spec,          6)
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_CALLBACK pb_default_field_callback
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_SigningKeyPair_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  private_key,       2)
#define com_digitalasset_canton_crypto_v30_SigningKeyPair_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_SigningKeyPair_DEFAULT NULL
#define com_digitalasset_canton_crypto_v30_SigningKeyPair_private_key_MSGTYPE com_digitalasset_canton_crypto_v30_SigningPrivateKey

#define com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UENUM,    algorithms,        1) \
X(a, CALLBACK, REPEATED, UENUM,    keys,              2)
#define com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_CALLBACK pb_default_field_callback
#define com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    format,            2) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,        3) \
X(a, STATIC,   SINGULAR, UENUM,    scheme,            4) \
X(a, STATIC,   SINGULAR, UENUM,    key_spec,          5)
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    format,            2) \
X(a, STATIC,   SINGULAR, BYTES,    private_key,       3) \
X(a, STATIC,   SINGULAR, UENUM,    scheme,            4) \
X(a, STATIC,   SINGULAR, UENUM,    key_spec,          5)
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_EncryptionKeyPair_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  private_key,       2)
#define com_digitalasset_canton_crypto_v30_EncryptionKeyPair_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_EncryptionKeyPair_DEFAULT NULL
#define com_digitalasset_canton_crypto_v30_EncryptionKeyPair_private_key_MSGTYPE com_digitalasset_canton_crypto_v30_EncryptionPrivateKey

#define com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UENUM,    algorithms,        1) \
X(a, CALLBACK, REPEATED, UENUM,    keys,              2)
#define com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_CALLBACK pb_default_field_callback
#define com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_CryptoKeyPair_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pair,signing_key_pair,pair.signing_key_pair),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pair,encryption_key_pair,pair.encryption_key_pair),   2)
#define com_digitalasset_canton_crypto_v30_CryptoKeyPair_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_CryptoKeyPair_DEFAULT NULL
#define com_digitalasset_canton_crypto_v30_CryptoKeyPair_pair_signing_key_pair_MSGTYPE com_digitalasset_canton_crypto_v30_SigningKeyPair
#define com_digitalasset_canton_crypto_v30_CryptoKeyPair_pair_encryption_key_pair_MSGTYPE com_digitalasset_canton_crypto_v30_EncryptionKeyPair

#define com_digitalasset_canton_crypto_v30_SymmetricKey_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    format,            1) \
X(a, STATIC,   SINGULAR, BYTES,    key,               2) \
X(a, STATIC,   SINGULAR, UENUM,    scheme,            3)
#define com_digitalasset_canton_crypto_v30_SymmetricKey_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_SymmetricKey_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    ciphertext,        1) \
X(a, STATIC,   SINGULAR, UENUM,    symmetric_key_scheme,   2) \
X(a, STATIC,   SINGULAR, UENUM,    pbkdf_scheme,      3) \
X(a, STATIC,   SINGULAR, BYTES,    salt,              4)
#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    ciphertext,        1) \
X(a, STATIC,   SINGULAR, UENUM,    encryption_algorithm_spec,   2) \
X(a, STATIC,   SINGULAR, STRING,   fingerprint,       3)
#define com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_CALLBACK NULL
#define com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_DEFAULT NULL

#define com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  keys,              1) \
X(a, STATIC,   SINGULAR, UINT32,   threshold,         2)
#define com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_CALLBACK pb_default_field_callback
#define com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_DEFAULT NULL
#define com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_keys_MSGTYPE com_digitalasset_canton_crypto_v30_SigningPublicKey

extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_Hmac_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_Salt_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_Signature_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_SignatureDelegation_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_PublicKey_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_PublicKeyWithName_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_PrivateKey_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_SigningPublicKey_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_SigningPrivateKey_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_SigningKeyPair_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_EncryptionPublicKey_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_EncryptionKeyPair_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_CryptoKeyPair_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_SymmetricKey_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_msg;
extern const pb_msgdesc_t com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_digitalasset_canton_crypto_v30_Hmac_fields &com_digitalasset_canton_crypto_v30_Hmac_msg
#define com_digitalasset_canton_crypto_v30_Salt_fields &com_digitalasset_canton_crypto_v30_Salt_msg
#define com_digitalasset_canton_crypto_v30_Signature_fields &com_digitalasset_canton_crypto_v30_Signature_msg
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_fields &com_digitalasset_canton_crypto_v30_SignatureDelegation_msg
#define com_digitalasset_canton_crypto_v30_PublicKey_fields &com_digitalasset_canton_crypto_v30_PublicKey_msg
#define com_digitalasset_canton_crypto_v30_PublicKeyWithName_fields &com_digitalasset_canton_crypto_v30_PublicKeyWithName_msg
#define com_digitalasset_canton_crypto_v30_PrivateKey_fields &com_digitalasset_canton_crypto_v30_PrivateKey_msg
#define com_digitalasset_canton_crypto_v30_SigningPublicKey_fields &com_digitalasset_canton_crypto_v30_SigningPublicKey_msg
#define com_digitalasset_canton_crypto_v30_SigningPrivateKey_fields &com_digitalasset_canton_crypto_v30_SigningPrivateKey_msg
#define com_digitalasset_canton_crypto_v30_SigningKeyPair_fields &com_digitalasset_canton_crypto_v30_SigningKeyPair_msg
#define com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_fields &com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_msg
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_fields &com_digitalasset_canton_crypto_v30_EncryptionPublicKey_msg
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_fields &com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_msg
#define com_digitalasset_canton_crypto_v30_EncryptionKeyPair_fields &com_digitalasset_canton_crypto_v30_EncryptionKeyPair_msg
#define com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_fields &com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_msg
#define com_digitalasset_canton_crypto_v30_CryptoKeyPair_fields &com_digitalasset_canton_crypto_v30_CryptoKeyPair_msg
#define com_digitalasset_canton_crypto_v30_SymmetricKey_fields &com_digitalasset_canton_crypto_v30_SymmetricKey_msg
#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_fields &com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_msg
#define com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_fields &com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_msg
#define com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_fields &com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_msg

/* Maximum encoded size of messages (where known) */
/* com_digitalasset_canton_crypto_v30_PublicKey_size depends on runtime parameters */
/* com_digitalasset_canton_crypto_v30_PublicKeyWithName_size depends on runtime parameters */
/* com_digitalasset_canton_crypto_v30_PrivateKey_size depends on runtime parameters */
/* com_digitalasset_canton_crypto_v30_SigningPublicKey_size depends on runtime parameters */
/* com_digitalasset_canton_crypto_v30_SigningPrivateKey_size depends on runtime parameters */
/* com_digitalasset_canton_crypto_v30_SigningKeyPair_size depends on runtime parameters */
/* com_digitalasset_canton_crypto_v30_RequiredSigningSpecs_size depends on runtime parameters */
/* com_digitalasset_canton_crypto_v30_RequiredEncryptionSpecs_size depends on runtime parameters */
/* com_digitalasset_canton_crypto_v30_CryptoKeyPair_size depends on runtime parameters */
/* com_digitalasset_canton_crypto_v30_SigningKeysWithThreshold_size depends on runtime parameters */
#define COM_DIGITALASSET_CANTON_CRYPTO_V30_COM_DIGITALASSET_CANTON_CRYPTO_V30_CRYPTO_PB_H_MAX_SIZE com_digitalasset_canton_crypto_v30_Signature_size
#define com_digitalasset_canton_crypto_v30_AsymmetricEncrypted_size 2055
#define com_digitalasset_canton_crypto_v30_EncryptionKeyPair_size 2063
#define com_digitalasset_canton_crypto_v30_EncryptionPrivateKey_size 2060
#define com_digitalasset_canton_crypto_v30_EncryptionPublicKey_size 1034
#define com_digitalasset_canton_crypto_v30_Hmac_size 1029
#define com_digitalasset_canton_crypto_v30_PasswordBasedEncrypted_size 2058
#define com_digitalasset_canton_crypto_v30_Salt_size 1029
#define com_digitalasset_canton_crypto_v30_SignatureDelegation_size 2078
#define com_digitalasset_canton_crypto_v30_Signature_size 4139
#define com_digitalasset_canton_crypto_v30_SymmetricKey_size 1032

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
