/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_DAML_LEDGER_API_V2_INTERACTIVE_COM_DAML_LEDGER_API_V2_INTERACTIVE_DEVICE_PB_H_INCLUDED
#define PB_COM_DAML_LEDGER_API_V2_INTERACTIVE_COM_DAML_LEDGER_API_V2_INTERACTIVE_DEVICE_PB_H_INCLUDED
#include <pb.h>
#include "com/daml/ledger/api/v2/interactive/interactive_submission_common_data.pb.h"
#include "com/daml/ledger/api/v2/interactive/transaction/v1/interactive_submission_data.pb.h"
#include "com/daml/ledger/api/v2/interactive/transaction/v1/interactive_submission_data_cb.pb.h"
#include "com/daml/ledger/api/v2/value.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Device variant of Daml Transaction.
 This represents the effect on the ledger if this transaction is successfully committed. */
typedef struct _com_daml_ledger_api_v2_interactive_DeviceDamlTransaction {
    /* Transaction version, will be >= max(nodes version) */
    char *version;
    /* Root nodes of the transaction */
    pb_size_t roots_count;
    char **roots;
    /* Number of nodes in the transaction */
    int32_t nodes_count;
    /* Node seeds are values associated with certain nodes used for generating cryptographic salts */
    pb_size_t node_seeds_count;
    struct _com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed *node_seeds;
} com_daml_ledger_api_v2_interactive_DeviceDamlTransaction;

typedef struct _com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed {
    int32_t node_id;
    pb_bytes_array_t *seed;
} com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed;

/* A transaction may contain nodes with different versions.
 Each node must be hashed using the hashing algorithm corresponding to its specific version.
 [docs-entry-start: DamlTransaction.Node] */
typedef struct _com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node {
    pb_callback_t node_id;
    pb_callback_t cb_versioned_node;
    pb_size_t which_versioned_node;
    union {
        /* Start at 1000 so we can add more fields before if necessary
     When new versions will be added, they will show here */
        com_daml_ledger_api_v2_interactive_transaction_v1_Node v1;
    };
} com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node;

typedef struct _com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay {
    /* Transaction version, will be >= max(nodes version) */
    char *version;
    /* Root nodes of the transaction */
    pb_size_t roots_count;
    char **roots;
    /* Number of nodes in the transaction */
    int32_t nodes_count;
    /* Node seeds are values associated with certain nodes used for generating cryptographic salts */
    pb_size_t node_seeds_count;
    struct _com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed *node_seeds;
} com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay;

typedef struct _com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed {
    int32_t node_id;
    pb_bytes_array_t *seed;
} com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed;

/* A transaction may contain nodes with different versions.
 Each node must be hashed using the hashing algorithm corresponding to its specific version.
 [docs-entry-start: DamlTransaction.Node] */
typedef struct _com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node {
    pb_callback_t node_id;
    pb_callback_t cb_versioned_node;
    pb_size_t which_versioned_node;
    union {
        /* Start at 1000 so we can add more fields before if necessary
     When new versions will be added, they will show here */
        com_daml_ledger_api_v2_interactive_transaction_v1_cb_NodeDisplay v1;
    };
} com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node;

typedef struct _com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo {
    pb_size_t act_as_count;
    char **act_as;
    char *command_id;
} com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo;

/* Device variant of Transaction Metadata
 Refer to the hashing documentation for information on how it should be hashed. */
typedef struct _com_daml_ledger_api_v2_interactive_DeviceMetadata {
    bool has_submitter_info;
    com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo submitter_info;
    char *synchronizer_id;
    uint32_t mediator_group;
    char *transaction_uuid;
    uint64_t preparation_time;
    int32_t input_contracts_count;
    /* Where ledger time constraints are imposed during the execution of the contract they will be populated
 in the fields below. These are optional because if the transaction does NOT depend on time, these values
 do not need to be set.
 The final ledger effective time used will be chosen when the command is submitted through the [execute] RPC.
 If the ledger effective time is outside of any populated min/max bounds then a different transaction
 can result, that will cause a confirmation message rejection. */
    bool has_min_ledger_effective_time;
    uint64_t min_ledger_effective_time;
    bool has_max_ledger_effective_time;
    uint64_t max_ledger_effective_time;
} com_daml_ledger_api_v2_interactive_DeviceMetadata;

typedef struct _com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry {
    bool has_key;
    com_daml_ledger_api_v2_interactive_GlobalKey key;
    bool has_value;
    com_daml_ledger_api_v2_Value value;
} com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry;

typedef struct _com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract {
    pb_callback_t cb_contract;
    pb_size_t which_contract;
    union {
        /* When new versions will be added, they will show here */
        com_daml_ledger_api_v2_interactive_transaction_v1_Create v1;
    };
    uint64_t created_at;
} com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_init_default {NULL, 0, NULL, 0, 0, NULL}
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed_init_default {0, NULL}
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0, {com_daml_ledger_api_v2_interactive_transaction_v1_Node_init_default}}
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_init_default {NULL, 0, NULL, 0, 0, NULL}
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed_init_default {0, NULL}
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0, {com_daml_ledger_api_v2_interactive_transaction_v1_cb_NodeDisplay_init_default}}
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_init_default {false, com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_init_default, NULL, 0, NULL, 0, 0, false, 0, false, 0}
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_init_default {0, NULL, NULL}
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_init_default {false, com_daml_ledger_api_v2_interactive_GlobalKey_init_default, false, com_daml_ledger_api_v2_Value_init_default}
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_init_default {{{NULL}, NULL}, 0, {com_daml_ledger_api_v2_interactive_transaction_v1_Create_init_default}, 0}
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_init_zero {NULL, 0, NULL, 0, 0, NULL}
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed_init_zero {0, NULL}
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, 0, {com_daml_ledger_api_v2_interactive_transaction_v1_Node_init_zero}}
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_init_zero {NULL, 0, NULL, 0, 0, NULL}
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed_init_zero {0, NULL}
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, 0, {com_daml_ledger_api_v2_interactive_transaction_v1_cb_NodeDisplay_init_zero}}
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_init_zero {false, com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_init_zero, NULL, 0, NULL, 0, 0, false, 0, false, 0}
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_init_zero {0, NULL, NULL}
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_init_zero {false, com_daml_ledger_api_v2_interactive_GlobalKey_init_zero, false, com_daml_ledger_api_v2_Value_init_zero}
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_init_zero {{{NULL}, NULL}, 0, {com_daml_ledger_api_v2_interactive_transaction_v1_Create_init_zero}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_version_tag 1
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_roots_tag 2
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_nodes_count_tag 3
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_node_seeds_tag 4
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed_node_id_tag 1
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed_seed_tag 2
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_node_id_tag 1
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_v1_tag 1000
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_version_tag 1
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_roots_tag 2
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_nodes_count_tag 3
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_node_seeds_tag 4
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed_node_id_tag 1
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed_seed_tag 2
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_node_id_tag 1
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_v1_tag 1000
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_act_as_tag 1
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_command_id_tag 2
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_submitter_info_tag 2
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_synchronizer_id_tag 3
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_mediator_group_tag 4
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_transaction_uuid_tag 5
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_preparation_time_tag 6
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_input_contracts_count_tag 7
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_min_ledger_effective_time_tag 9
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_max_ledger_effective_time_tag 10
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_key_tag 1
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_value_tag 2
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_v1_tag 1
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_created_at_tag 1000

/* Struct field encoding specification for nanopb */
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   version,           1) \
X(a, POINTER,  REPEATED, STRING,   roots,             2) \
X(a, STATIC,   SINGULAR, INT32,    nodes_count,       3) \
X(a, POINTER,  REPEATED, MESSAGE,  node_seeds,        4)
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_node_seeds_MSGTYPE com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed

#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    node_id,           1) \
X(a, POINTER,  SINGULAR, BYTES,    seed,              2)
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed_DEFAULT NULL

#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (versioned_node,v1,v1), 1000)
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_versioned_node_v1_MSGTYPE com_daml_ledger_api_v2_interactive_transaction_v1_Node

#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   version,           1) \
X(a, POINTER,  REPEATED, STRING,   roots,             2) \
X(a, STATIC,   SINGULAR, INT32,    nodes_count,       3) \
X(a, POINTER,  REPEATED, MESSAGE,  node_seeds,        4)
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_node_seeds_MSGTYPE com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed

#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    node_id,           1) \
X(a, POINTER,  SINGULAR, BYTES,    seed,              2)
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed_DEFAULT NULL

#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (versioned_node,v1,v1), 1000)
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_versioned_node_v1_MSGTYPE com_daml_ledger_api_v2_interactive_transaction_v1_cb_NodeDisplay

#define com_daml_ledger_api_v2_interactive_DeviceMetadata_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  submitter_info,    2) \
X(a, POINTER,  SINGULAR, STRING,   synchronizer_id,   3) \
X(a, STATIC,   SINGULAR, UINT32,   mediator_group,    4) \
X(a, POINTER,  SINGULAR, STRING,   transaction_uuid,   5) \
X(a, STATIC,   SINGULAR, UINT64,   preparation_time,   6) \
X(a, STATIC,   SINGULAR, INT32,    input_contracts_count,   7) \
X(a, STATIC,   OPTIONAL, UINT64,   min_ledger_effective_time,   9) \
X(a, STATIC,   OPTIONAL, UINT64,   max_ledger_effective_time,  10)
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_submitter_info_MSGTYPE com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo

#define com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, STRING,   act_as,            1) \
X(a, POINTER,  SINGULAR, STRING,   command_id,        2)
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_DEFAULT NULL

#define com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_key_MSGTYPE com_daml_ledger_api_v2_interactive_GlobalKey
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_value_MSGTYPE com_daml_ledger_api_v2_Value

#define com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (contract,v1,v1),   1) \
X(a, STATIC,   SINGULAR, UINT64,   created_at,      1000)
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_contract_v1_MSGTYPE com_daml_ledger_api_v2_interactive_transaction_v1_Create

extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DeviceMetadata_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_fields &com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_msg
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed_fields &com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed_msg
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_fields &com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_msg
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_fields &com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_msg
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed_fields &com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed_msg
#define com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_fields &com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_msg
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_fields &com_daml_ledger_api_v2_interactive_DeviceMetadata_msg
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_fields &com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_msg
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_fields &com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_msg
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_fields &com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_msg

/* Maximum encoded size of messages (where known) */
#if defined(com_daml_ledger_api_v2_interactive_transaction_v1_Node_size)
#endif
#if defined(com_daml_ledger_api_v2_interactive_transaction_v1_cb_NodeDisplay_size)
#endif
#if defined(com_daml_ledger_api_v2_interactive_transaction_v1_Create_size)
#endif
/* com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_NodeSeed_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_DeviceDamlTransaction_Node_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_NodeSeed_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_DeviceDamlTransactionDisplay_Node_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_DeviceMetadata_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_DeviceMetadata_SubmitterInfo_size depends on runtime parameters */
#if defined(com_daml_ledger_api_v2_interactive_GlobalKey_size) && defined(com_daml_ledger_api_v2_Value_size)
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_GlobalKeyMappingEntry_size (12 + com_daml_ledger_api_v2_interactive_GlobalKey_size + com_daml_ledger_api_v2_Value_size)
#endif
#if defined(com_daml_ledger_api_v2_interactive_transaction_v1_Create_size)
#define COM_DAML_LEDGER_API_V2_INTERACTIVE_COM_DAML_LEDGER_API_V2_INTERACTIVE_DEVICE_PB_H_MAX_SIZE com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_size
#define com_daml_ledger_api_v2_interactive_DeviceMetadata_InputContract_size (18 + com_daml_ledger_api_v2_interactive_transaction_v1_Create_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
